# Generated by Django 5.0 on 2025-12-04 07:54

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PlantillaNotificacion',
            fields=[
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, verbose_name='Fecha de Actualización')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tipo', models.CharField(max_length=50, unique=True, verbose_name='Tipo de Notificación')),
                ('nombre', models.CharField(max_length=200, verbose_name='Nombre')),
                ('titulo_plantilla', models.CharField(help_text='Usa {{variable}} para variables dinámicas', max_length=255, verbose_name='Plantilla de Título')),
                ('mensaje_plantilla', models.TextField(help_text='Usa {{variable}} para variables dinámicas', verbose_name='Plantilla de Mensaje')),
                ('asunto_email', models.CharField(max_length=255, verbose_name='Asunto del Email')),
                ('cuerpo_email', models.TextField(help_text='Soporta HTML. Usa {{variable}} para variables dinámicas', verbose_name='Cuerpo del Email (HTML)')),
                ('enviar_email', models.BooleanField(default=True, verbose_name='Enviar Email')),
                ('prioridad_default', models.CharField(choices=[('baja', 'Baja'), ('normal', 'Normal'), ('alta', 'Alta'), ('urgente', 'Urgente')], default='normal', max_length=20, verbose_name='Prioridad por Defecto')),
            ],
            options={
                'verbose_name': 'Plantilla de Notificación',
                'verbose_name_plural': 'Plantillas de Notificación',
                'db_table': 'plantillas_notificacion',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Notificacion',
            fields=[
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, verbose_name='Fecha de Actualización')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tipo', models.CharField(choices=[('asignacion_evaluacion', 'Asignación de Evaluación'), ('asignacion_dimension', 'Asignación de Dimensión'), ('recordatorio_plazo', 'Recordatorio de Plazo'), ('evaluacion_completada', 'Evaluación Completada'), ('evaluacion_vencida', 'Evaluación Vencida'), ('comentario', 'Nuevo Comentario'), ('aprobacion', 'Solicitud de Aprobación'), ('sistema', 'Notificación del Sistema')], max_length=50, verbose_name='Tipo')),
                ('titulo', models.CharField(max_length=255, verbose_name='Título')),
                ('mensaje', models.TextField(verbose_name='Mensaje')),
                ('prioridad', models.CharField(choices=[('baja', 'Baja'), ('normal', 'Normal'), ('alta', 'Alta'), ('urgente', 'Urgente')], default='normal', max_length=20, verbose_name='Prioridad')),
                ('leida', models.BooleanField(default=False, verbose_name='Leída')),
                ('fecha_leida', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Lectura')),
                ('email_enviado', models.BooleanField(default=False, verbose_name='Email Enviado')),
                ('fecha_email_enviado', models.DateTimeField(blank=True, null=True, verbose_name='Fecha Email Enviado')),
                ('datos_adicionales', models.JSONField(blank=True, default=dict, help_text='Información adicional como IDs, enlaces, etc.', verbose_name='Datos Adicionales')),
                ('url_accion', models.CharField(blank=True, help_text='URL a la que redirigir cuando se hace clic en la notificación', max_length=500, verbose_name='URL de Acción')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notificaciones', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Notificación',
                'verbose_name_plural': 'Notificaciones',
                'db_table': 'notificaciones',
                'ordering': ['-fecha_creacion'],
                'indexes': [models.Index(fields=['usuario', 'leida'], name='notificacio_usuario_ef49b7_idx'), models.Index(fields=['tipo'], name='notificacio_tipo_f5d897_idx'), models.Index(fields=['prioridad'], name='notificacio_priorid_eb1da5_idx'), models.Index(fields=['fecha_creacion'], name='notificacio_fecha_c_24f290_idx')],
            },
        ),
    ]
