# Generated by Django 5.0 on 2026-01-29 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notificaciones', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificacion',
            name='tipo',
            field=models.CharField(choices=[('asignacion_evaluacion', 'Asignación de Evaluación'), ('asignacion_dimension', 'Asignación de Dimensión'), ('recordatorio_plazo', 'Recordatorio de Plazo'), ('evaluacion_completada', 'Evaluación Completada'), ('evaluacion_vencida', 'Evaluación Vencida'), ('comentario', 'Nuevo Comentario'), ('aprobacion', 'Solicitud de Aprobación'), ('sistema', 'Notificación del Sistema'), ('proyecto_en_validacion', 'Proyecto en Validación'), ('gap_aprobado', 'GAP Aprobado'), ('gap_rechazado', 'GAP Rechazado'), ('mensaje_personalizado', 'Mensaje Personalizado'), ('anuncio', 'Anuncio')], max_length=50, verbose_name='Tipo'),
        ),
    ]
