# Generated by Django 5.0 on 2026-02-17 07:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('empresas', '0002_empresa_pais_empresa_pais_otro_empresa_sector_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Framework',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(help_text='Código único (ISO27001, ISO27701, DAMADMBOK)', max_length=50, unique=True, verbose_name='Código')),
                ('nombre', models.CharField(help_text='Ejemplo: ISO 27001 - SGSI', max_length=200, verbose_name='Nombre')),
                ('descripcion', models.TextField(blank=True, verbose_name='Descripción')),
                ('version', models.CharField(blank=True, max_length=50, verbose_name='Versión')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, verbose_name='Fecha de Actualización')),
            ],
            options={
                'verbose_name': 'Framework',
                'verbose_name_plural': 'Frameworks',
                'db_table': 'frameworks',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Evaluacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=300, verbose_name='Nombre de la Evaluación')),
                ('descripcion', models.TextField(blank=True, verbose_name='Descripción')),
                ('nivel_deseado', models.IntegerField(choices=[(1, 'Nivel 1 - Inicial'), (2, 'Nivel 2 - Gestionado'), (3, 'Nivel 3 - Definido'), (4, 'Nivel 4 - Cuantitativamente Gestionado'), (5, 'Nivel 5 - Optimizado')], default=3, help_text='Nivel de madurez que la empresa quiere alcanzar con esta evaluación', verbose_name='Nivel Deseado')),
                ('estado', models.CharField(choices=[('disponible', 'Disponible'), ('configurando', 'Configurando'), ('en_proceso', 'En Proceso'), ('completada', 'Completada'), ('aprobada', 'Aprobada'), ('rechazada', 'Rechazada')], default='disponible', max_length=20, verbose_name='Estado')),
                ('usar_todas_preguntas', models.BooleanField(default=True, help_text='True = todas las preguntas de los frameworks. False = selección manual.', verbose_name='Usar Todas las Preguntas')),
                ('usar_respuestas_compartidas', models.BooleanField(default=True, help_text='Si es True, las respuestas se propagan automáticamente entre preguntas relacionadas', verbose_name='Usar Respuestas Compartidas')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, verbose_name='Fecha de Actualización')),
                ('creado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='evaluaciones_inteligentes_creadas', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
                ('empresa', models.ForeignKey(help_text='Empresa dueña de esta evaluación', on_delete=django.db.models.deletion.CASCADE, related_name='evaluaciones_inteligentes', to='empresas.empresa', verbose_name='Empresa')),
                ('frameworks', models.ManyToManyField(help_text='Frameworks incluidos (deben estar asignados a la empresa)', related_name='evaluaciones', to='evaluaciones.framework', verbose_name='Frameworks')),
            ],
            options={
                'verbose_name': 'Evaluación',
                'verbose_name_plural': 'Evaluaciones',
                'db_table': 'evaluaciones',
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='PreguntaEvaluacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('correlativo', models.IntegerField(help_text='Número único de pregunta en el Excel', verbose_name='Correlativo')),
                ('framework_base_nombre', models.CharField(blank=True, help_text='Ejemplo: ISO 27001 - SGSI, ISO 42001:2023 AIMS', max_length=200, verbose_name='Framework Base Nombre')),
                ('codigo_control', models.CharField(help_text='Ejemplo: A.5.1, 5.1, DG-01', max_length=100, verbose_name='Código Control')),
                ('seccion_general', models.CharField(help_text='Categoría o tema del control', max_length=500, verbose_name='Sección General')),
                ('nombre_control', models.TextField(verbose_name='Nombre del Control')),
                ('tags', models.TextField(blank=True, help_text='Etiquetas separadas por comas', verbose_name='Tags')),
                ('frameworks_referenciales', models.TextField(blank=True, help_text='Ejemplo: ISO 27001:2022:5.1, COBIT 2019:APO01.01', verbose_name='Frameworks y Controles Referenciales')),
                ('objetivo_evaluacion', models.TextField(help_text='Qué se busca verificar con esta pregunta', verbose_name='Objetivo de Evaluación')),
                ('pregunta', models.TextField(help_text='Pregunta detallada y exhaustiva', verbose_name='Pregunta de Evaluación')),
                ('nivel_madurez', models.IntegerField(choices=[(1, 'Nivel 1 - Inicial'), (2, 'Nivel 2 - Gestionado'), (3, 'Nivel 3 - Definido'), (4, 'Nivel 4 - Gestionado Cuantitativamente'), (5, 'Nivel 5 - Optimizado')], verbose_name='Nivel de Madurez')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, verbose_name='Fecha de Actualización')),
                ('framework', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='preguntas', to='evaluaciones.framework', verbose_name='Framework Base')),
            ],
            options={
                'verbose_name': 'Pregunta de Evaluación',
                'verbose_name_plural': 'Preguntas de Evaluación',
                'db_table': 'preguntas_evaluacion',
                'ordering': ['framework', 'correlativo'],
            },
        ),
        migrations.CreateModel(
            name='EvidenciaRequerida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.TextField(help_text='Ejemplo: 1. Documento formal de políticas...', verbose_name='Descripción de la Evidencia')),
                ('orden', models.IntegerField(help_text='Número de evidencia (1-5)', verbose_name='Orden')),
                ('pregunta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evidencias_requeridas', to='evaluaciones.preguntaevaluacion', verbose_name='Pregunta')),
            ],
            options={
                'verbose_name': 'Evidencia Requerida',
                'verbose_name_plural': 'Evidencias Requeridas',
                'db_table': 'evidencias_requeridas',
                'ordering': ['pregunta', 'orden'],
            },
        ),
        migrations.CreateModel(
            name='EvaluacionPregunta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orden', models.IntegerField(help_text='Orden de la pregunta en esta evaluación (1, 2, 3...)', verbose_name='Orden')),
                ('fecha_agregada', models.DateTimeField(auto_now_add=True, verbose_name='Fecha Agregada')),
                ('evaluacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='preguntas_seleccionadas', to='evaluaciones.evaluacion', verbose_name='Evaluación')),
                ('pregunta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='en_evaluaciones', to='evaluaciones.preguntaevaluacion', verbose_name='Pregunta')),
            ],
            options={
                'verbose_name': 'Pregunta en Evaluación',
                'verbose_name_plural': 'Preguntas en Evaluaciones',
                'db_table': 'evaluacion_preguntas',
                'ordering': ['evaluacion', 'orden'],
            },
        ),
        migrations.CreateModel(
            name='RelacionFramework',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('referencia_textual', models.CharField(help_text='Ejemplo: ISO 27001:2022:5.1 o COBIT 2019:APO01.01', max_length=1000, verbose_name='Referencia Textual')),
                ('codigo_control_referenciado', models.CharField(blank=True, help_text='Ejemplo: 5.1, APO01.01, Business Principles', max_length=200, verbose_name='Código Control Referenciado')),
                ('porcentaje_cobertura', models.IntegerField(default=100, help_text='Qué tanto esta pregunta cubre la referencia (0-100)', verbose_name='Porcentaje de Cobertura')),
                ('framework_destino', models.ForeignKey(help_text='Framework referenciado', on_delete=django.db.models.deletion.CASCADE, related_name='referencias_desde_otros', to='evaluaciones.framework', verbose_name='Framework Destino')),
                ('pregunta_origen', models.ForeignKey(help_text='Pregunta que referencia a otros frameworks', on_delete=django.db.models.deletion.CASCADE, related_name='relaciones_frameworks', to='evaluaciones.preguntaevaluacion', verbose_name='Pregunta Origen')),
            ],
            options={
                'verbose_name': 'Relación entre Frameworks',
                'verbose_name_plural': 'Relaciones entre Frameworks',
                'db_table': 'relaciones_frameworks',
            },
        ),
        migrations.CreateModel(
            name='RespuestaEvaluacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('respuesta', models.CharField(choices=[('cumple', 'Cumple Totalmente'), ('cumple_parcial', 'Cumple Parcialmente'), ('no_cumple', 'No Cumple'), ('no_aplica', 'No Aplica'), ('en_progreso', 'En Progreso')], max_length=20, verbose_name='Respuesta')),
                ('observaciones', models.TextField(blank=True, verbose_name='Observaciones')),
                ('es_respuesta_original', models.BooleanField(default=True, verbose_name='Es Respuesta Original')),
                ('fecha_respuesta', models.DateTimeField(auto_now=True, verbose_name='Fecha de Respuesta')),
                ('evaluacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='respuestas', to='evaluaciones.evaluacion', verbose_name='Evaluación')),
                ('heredada_de', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='respuestas_heredadas', to='evaluaciones.respuestaevaluacion', verbose_name='Heredada De')),
                ('pregunta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='respuestas', to='evaluaciones.preguntaevaluacion', verbose_name='Pregunta')),
                ('respondido_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='respuestas_evaluaciones_dadas', to=settings.AUTH_USER_MODEL, verbose_name='Respondido Por')),
            ],
            options={
                'verbose_name': 'Respuesta de Evaluación',
                'verbose_name_plural': 'Respuestas de Evaluación',
                'db_table': 'respuestas_evaluacion',
                'ordering': ['-fecha_respuesta'],
            },
        ),
        migrations.CreateModel(
            name='NotaEvidencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nota', models.TextField(help_text='Descripción de cómo se cumple con esta evidencia', verbose_name='Nota/Sugerencia')),
                ('referencia_documento', models.CharField(blank=True, help_text='Ej: POL-SEG-001, PROC-GRC-002', max_length=255, verbose_name='Referencia a Documento')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, verbose_name='Fecha de Actualización')),
                ('creado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notas_evidencias_creadas', to=settings.AUTH_USER_MODEL, verbose_name='Creado Por')),
                ('evidencia_requerida', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notas_usuario', to='evaluaciones.evidenciarequerida', verbose_name='Evidencia Requerida')),
                ('respuesta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notas_evidencias', to='evaluaciones.respuestaevaluacion', verbose_name='Respuesta')),
            ],
            options={
                'verbose_name': 'Nota de Evidencia',
                'verbose_name_plural': 'Notas de Evidencias',
                'db_table': 'notas_evidencias',
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='ComentarioEvaluacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comentario', models.TextField(verbose_name='Comentario')),
                ('es_interno', models.BooleanField(default=False, verbose_name='Es Interno')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('creado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='comentarios_evaluaciones_creados', to=settings.AUTH_USER_MODEL, verbose_name='Creado Por')),
                ('evaluacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comentarios', to='evaluaciones.evaluacion', verbose_name='Evaluación')),
                ('respuesta', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comentarios', to='evaluaciones.respuestaevaluacion', verbose_name='Respuesta')),
            ],
            options={
                'verbose_name': 'Comentario de Evaluación',
                'verbose_name_plural': 'Comentarios de Evaluación',
                'db_table': 'comentarios_evaluacion',
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='EmpresaFramework',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_asignacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Asignación')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('notas', models.TextField(blank=True, verbose_name='Notas')),
                ('asignado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='frameworks_asignados_por_mi', to=settings.AUTH_USER_MODEL, verbose_name='Asignado por')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='frameworks_asignados', to='empresas.empresa', verbose_name='Empresa')),
                ('framework', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='empresas_asignadas', to='evaluaciones.framework', verbose_name='Framework')),
            ],
            options={
                'verbose_name': 'Framework Asignado a Empresa',
                'verbose_name_plural': 'Frameworks Asignados a Empresas',
                'db_table': 'empresa_frameworks',
                'ordering': ['empresa', 'framework'],
                'indexes': [models.Index(fields=['empresa', 'activo'], name='empresa_fra_empresa_1b3913_idx'), models.Index(fields=['framework'], name='empresa_fra_framewo_f6b475_idx')],
                'unique_together': {('empresa', 'framework')},
            },
        ),
        migrations.AddIndex(
            model_name='preguntaevaluacion',
            index=models.Index(fields=['framework', 'correlativo'], name='preguntas_e_framewo_163f6d_idx'),
        ),
        migrations.AddIndex(
            model_name='preguntaevaluacion',
            index=models.Index(fields=['codigo_control'], name='preguntas_e_codigo__12b22e_idx'),
        ),
        migrations.AddIndex(
            model_name='preguntaevaluacion',
            index=models.Index(fields=['nivel_madurez'], name='preguntas_e_nivel_m_c3cd2a_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='preguntaevaluacion',
            unique_together={('framework', 'correlativo')},
        ),
        migrations.AlterUniqueTogether(
            name='evidenciarequerida',
            unique_together={('pregunta', 'orden')},
        ),
        migrations.AddIndex(
            model_name='evaluacionpregunta',
            index=models.Index(fields=['evaluacion', 'orden'], name='evaluacion__evaluac_bfa1d3_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='evaluacionpregunta',
            unique_together={('evaluacion', 'pregunta')},
        ),
        migrations.AddIndex(
            model_name='relacionframework',
            index=models.Index(fields=['pregunta_origen'], name='relaciones__pregunt_f608cf_idx'),
        ),
        migrations.AddIndex(
            model_name='relacionframework',
            index=models.Index(fields=['framework_destino'], name='relaciones__framewo_1ec04f_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='relacionframework',
            unique_together={('pregunta_origen', 'referencia_textual')},
        ),
        migrations.AlterUniqueTogether(
            name='respuestaevaluacion',
            unique_together={('evaluacion', 'pregunta')},
        ),
    ]
