# Generated by Django 5.0 on 2026-02-19 19:01

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('empresas', '0002_empresa_pais_empresa_pais_otro_empresa_sector_and_more'),
        ('evaluaciones', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AsignacionEvaluacionIQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_asignacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Asignación')),
                ('fecha_inicio', models.DateField(help_text='Fecha desde la cual el usuario puede empezar', verbose_name='Fecha de Inicio')),
                ('fecha_limite', models.DateField(help_text='Fecha máxima para completar la evaluación', verbose_name='Fecha Límite')),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('en_progreso', 'En Progreso'), ('completada', 'Completada'), ('revisada', 'Revisada'), ('aprobada', 'Aprobada'), ('rechazada', 'Rechazada'), ('vencida', 'Vencida')], default='pendiente', max_length=20, verbose_name='Estado')),
                ('fecha_inicio_real', models.DateTimeField(blank=True, help_text='Momento en que el usuario comenzó a responder', null=True, verbose_name='Fecha Real de Inicio')),
                ('fecha_completado', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Completado')),
                ('fecha_revision', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Revisión')),
                ('total_preguntas', models.IntegerField(default=0, verbose_name='Total de Preguntas')),
                ('preguntas_respondidas', models.IntegerField(default=0, verbose_name='Preguntas Respondidas')),
                ('porcentaje_completado', models.DecimalField(decimal_places=2, default=0, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Porcentaje Completado')),
                ('notas_asignacion', models.TextField(blank=True, help_text='Instrucciones o comentarios para el usuario', verbose_name='Notas de Asignación')),
                ('notas_revision', models.TextField(blank=True, help_text='Comentarios del revisor', verbose_name='Notas de Revisión')),
                ('notificar_usuario', models.BooleanField(default=True, help_text='Enviar email al asignar', verbose_name='Notificar al Usuario')),
                ('recordatorio_enviado', models.BooleanField(default=False, verbose_name='Recordatorio Enviado')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, verbose_name='Última Actualización')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('asignado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='asignaciones_iq_creadas', to=settings.AUTH_USER_MODEL, verbose_name='Asignado Por')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asignaciones_evaluaciones', to='empresas.empresa', verbose_name='Empresa')),
                ('evaluacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asignaciones', to='evaluaciones.evaluacion', verbose_name='Evaluación')),
                ('revisado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='asignaciones_iq_revisadas', to=settings.AUTH_USER_MODEL, verbose_name='Revisado Por')),
                ('usuario_asignado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluaciones_asignadas', to=settings.AUTH_USER_MODEL, verbose_name='Usuario Asignado')),
            ],
            options={
                'verbose_name': 'Asignación de Evaluación',
                'verbose_name_plural': 'Asignaciones de Evaluaciones',
                'ordering': ['-fecha_asignacion'],
            },
        ),
        migrations.CreateModel(
            name='ProgresoAsignacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('respondida', models.BooleanField(default=False, verbose_name='Respondida')),
                ('fecha_respuesta', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Respuesta')),
                ('tiempo_respuesta_minutos', models.IntegerField(blank=True, null=True, verbose_name='Tiempo de Respuesta (min)')),
                ('asignacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progreso_detallado', to='asignaciones_iq.asignacionevaluacioniq', verbose_name='Asignación')),
                ('pregunta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='evaluaciones.preguntaevaluacion', verbose_name='Pregunta')),
            ],
            options={
                'verbose_name': 'Progreso de Asignación',
                'verbose_name_plural': 'Progreso de Asignaciones',
                'ordering': ['pregunta__correlativo'],
            },
        ),
        migrations.AddIndex(
            model_name='asignacionevaluacioniq',
            index=models.Index(fields=['estado', 'fecha_limite'], name='asignacione_estado_9636b9_idx'),
        ),
        migrations.AddIndex(
            model_name='asignacionevaluacioniq',
            index=models.Index(fields=['usuario_asignado', 'estado'], name='asignacione_usuario_4221e2_idx'),
        ),
        migrations.AddIndex(
            model_name='asignacionevaluacioniq',
            index=models.Index(fields=['empresa', 'estado'], name='asignacione_empresa_905686_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='asignacionevaluacioniq',
            unique_together={('evaluacion', 'usuario_asignado')},
        ),
        migrations.AlterUniqueTogether(
            name='progresoasignacion',
            unique_together={('asignacion', 'pregunta')},
        ),
    ]
