# Generated by Django 5.0 on 2026-02-22 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asignaciones_iq', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='asignacionevaluacioniq',
            name='requiere_revision',
            field=models.BooleanField(default=True, help_text='Si es True, el Admin debe aprobar/rechazar. Si es False, se auto-aprueba al completar.', verbose_name='Requiere Revisión'),
        ),
    ]
