# Generated by Django 5.0 on 2026-02-23 03:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asignaciones_iq', '0002_asignacionevaluacioniq_requiere_revision'),
        ('evaluaciones', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RespuestaEvaluacionIQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('respuesta', models.CharField(choices=[('SI_CUMPLE', 'Sí Cumple'), ('CUMPLE_PARCIAL', 'Cumple Parcialmente'), ('NO_CUMPLE', 'No Cumple'), ('NO_APLICA', 'No Aplica')], max_length=20)),
                ('justificacion', models.TextField()),
                ('nivel_madurez', models.DecimalField(decimal_places=1, default=0.0, max_digits=2)),
                ('justificacion_madurez', models.TextField(blank=True, default='')),
                ('comentarios_adicionales', models.TextField(blank=True, default='')),
                ('es_respuesta_original', models.BooleanField(default=True)),
                ('fecha_respuesta', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('asignacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='respuestas_iq', to='asignaciones_iq.asignacionevaluacioniq', verbose_name='Asignación')),
                ('pregunta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='respuestas_iq', to='evaluaciones.preguntaevaluacion', verbose_name='Pregunta')),
                ('propagada_desde', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='respuestas_propagadas', to='asignaciones_iq.respuestaevaluacioniq')),
                ('respondido_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='respuestas_iq_creadas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Respuesta Evaluación IQ',
                'verbose_name_plural': 'Respuestas Evaluación IQ',
                'db_table': 'respuestas_evaluacion_iq',
                'ordering': ['-fecha_respuesta'],
                'unique_together': {('asignacion', 'pregunta')},
            },
        ),
    ]
