# Generated by Django 5.2.12 on 2026-03-12 03:45

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asignaciones_iq', '0003_respuestaevaluacioniq'),
        ('empresas', '0002_empresa_pais_empresa_pais_otro_empresa_sector_and_more'),
        ('evaluaciones', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CalculoNivelIQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('framework_id', models.IntegerField(verbose_name='Framework ID')),
                ('framework_nombre', models.CharField(max_length=200)),
                ('seccion', models.CharField(max_length=300, verbose_name='Sección / Dominio')),
                ('nivel_deseado', models.DecimalField(decimal_places=1, max_digits=2)),
                ('nivel_actual', models.DecimalField(decimal_places=1, max_digits=2)),
                ('gap', models.DecimalField(decimal_places=1, max_digits=3)),
                ('clasificacion_gap', models.CharField(choices=[('critico', 'Crítico'), ('alto', 'Alto'), ('medio', 'Medio'), ('bajo', 'Bajo'), ('cumplido', 'Cumplido'), ('superado', 'Superado')], max_length=20)),
                ('total_preguntas', models.IntegerField(default=0)),
                ('respuestas_si_cumple', models.IntegerField(default=0)),
                ('respuestas_cumple_parcial', models.IntegerField(default=0)),
                ('respuestas_no_cumple', models.IntegerField(default=0)),
                ('respuestas_no_aplica', models.IntegerField(default=0)),
                ('porcentaje_cumplimiento', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('calculado_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Cálculo de Nivel IQ',
                'verbose_name_plural': 'Cálculos de Nivel IQ',
                'db_table': 'calculos_nivel_iq',
                'ordering': ['-calculado_at'],
            },
        ),
        migrations.AlterUniqueTogether(
            name='progresoasignacion',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='progresoasignacion',
            name='asignacion',
        ),
        migrations.RemoveField(
            model_name='progresoasignacion',
            name='pregunta',
        ),
        migrations.AlterModelOptions(
            name='asignacionevaluacioniq',
            options={'ordering': ['-fecha_asignacion'], 'verbose_name': 'Asignación de Evaluación IQ', 'verbose_name_plural': 'Asignaciones de Evaluaciones IQ'},
        ),
        migrations.AlterModelOptions(
            name='respuestaevaluacioniq',
            options={'ordering': ['-respondido_at'], 'verbose_name': 'Respuesta Evaluación IQ', 'verbose_name_plural': 'Respuestas Evaluación IQ'},
        ),
        migrations.RemoveField(
            model_name='asignacionevaluacioniq',
            name='fecha_revision',
        ),
        migrations.RemoveField(
            model_name='respuestaevaluacioniq',
            name='fecha_actualizacion',
        ),
        migrations.RemoveField(
            model_name='respuestaevaluacioniq',
            name='fecha_respuesta',
        ),
        migrations.RemoveField(
            model_name='respuestaevaluacioniq',
            name='justificacion_madurez',
        ),
        migrations.AddField(
            model_name='asignacionevaluacioniq',
            name='auditado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='asignaciones_iq_auditadas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='asignacionevaluacioniq',
            name='fecha_auditada',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='asignacionevaluacioniq',
            name='notas_auditoria',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='respuestaevaluacioniq',
            name='auditado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='respuestas_iq_auditadas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='respuestaevaluacioniq',
            name='calificacion_auditor',
            field=models.CharField(blank=True, choices=[('SI_CUMPLE', 'Sí Cumple'), ('CUMPLE_PARCIAL', 'Cumple Parcialmente'), ('NO_CUMPLE', 'No Cumple')], max_length=20, null=True, verbose_name='Calificación del Auditor'),
        ),
        migrations.AddField(
            model_name='respuestaevaluacioniq',
            name='comentarios_auditor',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='respuestaevaluacioniq',
            name='estado',
            field=models.CharField(choices=[('borrador', 'Borrador'), ('enviado', 'Enviado'), ('auditado', 'Auditado')], default='borrador', max_length=20),
        ),
        migrations.AddField(
            model_name='respuestaevaluacioniq',
            name='fecha_auditoria',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='respuestaevaluacioniq',
            name='modificado_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='respuestaevaluacioniq',
            name='modificado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='respuestas_iq_modificadas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='respuestaevaluacioniq',
            name='recomendaciones_auditor',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='respuestaevaluacioniq',
            name='respondido_at',
            field=models.DateTimeField(auto_now_add=True, default='2024-01-01'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='respuestaevaluacioniq',
            name='version',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='asignacionevaluacioniq',
            name='activo',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='asignacionevaluacioniq',
            name='asignado_por',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='asignaciones_iq_creadas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='asignacionevaluacioniq',
            name='empresa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asignaciones_evaluaciones_iq', to='empresas.empresa', verbose_name='Empresa'),
        ),
        migrations.AlterField(
            model_name='asignacionevaluacioniq',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('en_progreso', 'En Progreso'), ('completada', 'Completada'), ('auditada', 'Auditada'), ('aprobada', 'Aprobada'), ('rechazada', 'Rechazada'), ('vencida', 'Vencida')], default='pendiente', max_length=20),
        ),
        migrations.AlterField(
            model_name='asignacionevaluacioniq',
            name='fecha_actualizacion',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='asignacionevaluacioniq',
            name='fecha_asignacion',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='asignacionevaluacioniq',
            name='fecha_completado',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='asignacionevaluacioniq',
            name='fecha_inicio',
            field=models.DateField(verbose_name='Fecha de Inicio'),
        ),
        migrations.AlterField(
            model_name='asignacionevaluacioniq',
            name='fecha_inicio_real',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='asignacionevaluacioniq',
            name='fecha_limite',
            field=models.DateField(verbose_name='Fecha Límite'),
        ),
        migrations.AlterField(
            model_name='asignacionevaluacioniq',
            name='notas_asignacion',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='asignacionevaluacioniq',
            name='notas_revision',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='asignacionevaluacioniq',
            name='notificar_usuario',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='asignacionevaluacioniq',
            name='porcentaje_completado',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='asignacionevaluacioniq',
            name='preguntas_respondidas',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='asignacionevaluacioniq',
            name='recordatorio_enviado',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='asignacionevaluacioniq',
            name='requiere_revision',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='asignacionevaluacioniq',
            name='revisado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='asignaciones_iq_revisadas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='asignacionevaluacioniq',
            name='total_preguntas',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='asignacionevaluacioniq',
            name='usuario_asignado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluaciones_iq_asignadas', to=settings.AUTH_USER_MODEL, verbose_name='Usuario Asignado'),
        ),
        migrations.AlterField(
            model_name='respuestaevaluacioniq',
            name='justificacion',
            field=models.TextField(help_text='Mínimo 10 caracteres. Obligatorio siempre.', verbose_name='Justificación'),
        ),
        migrations.AlterField(
            model_name='respuestaevaluacioniq',
            name='nivel_madurez',
            field=models.DecimalField(decimal_places=1, default=0.0, help_text='Asignado por el auditor (0–5, incrementos de 0.5)', max_digits=2, verbose_name='Nivel de Madurez'),
        ),
        migrations.AlterField(
            model_name='respuestaevaluacioniq',
            name='respuesta',
            field=models.CharField(blank=True, choices=[('NO_APLICA', 'No Aplica'), ('NO_CUMPLE', 'No Cumple')], default=None, max_length=20, null=True, verbose_name='Respuesta del Usuario'),
        ),
        migrations.AddIndex(
            model_name='respuestaevaluacioniq',
            index=models.Index(fields=['asignacion', 'estado'], name='respuestas__asignac_deb862_idx'),
        ),
        migrations.AddIndex(
            model_name='respuestaevaluacioniq',
            index=models.Index(fields=['pregunta'], name='respuestas__pregunt_e0640e_idx'),
        ),
        migrations.AddIndex(
            model_name='respuestaevaluacioniq',
            index=models.Index(fields=['respondido_por'], name='respuestas__respond_41a9d5_idx'),
        ),
        migrations.AddField(
            model_name='calculoniveliq',
            name='asignacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calculos_nivel_iq', to='asignaciones_iq.asignacionevaluacioniq', verbose_name='Asignación IQ'),
        ),
        migrations.AddField(
            model_name='calculoniveliq',
            name='empresa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calculos_nivel_iq', to='empresas.empresa'),
        ),
        migrations.AddField(
            model_name='calculoniveliq',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calculos_nivel_iq', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='ProgresoAsignacion',
        ),
        migrations.AddIndex(
            model_name='calculoniveliq',
            index=models.Index(fields=['empresa', 'framework_id'], name='calculos_ni_empresa_2f0564_idx'),
        ),
        migrations.AddIndex(
            model_name='calculoniveliq',
            index=models.Index(fields=['usuario', 'framework_id'], name='calculos_ni_usuario_a0ab87_idx'),
        ),
        migrations.AddIndex(
            model_name='calculoniveliq',
            index=models.Index(fields=['clasificacion_gap'], name='calculos_ni_clasifi_f6ee91_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='calculoniveliq',
            unique_together={('asignacion', 'seccion', 'framework_id')},
        ),
    ]
