# Generated by Django 5.0 on 2025-10-29 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='pais',
            field=models.CharField(choices=[('PE', 'Perú'), ('CO', 'Colombia'), ('CL', 'Chile'), ('AR', 'Argentina'), ('MX', 'México'), ('EC', 'Ecuador'), ('BO', 'Bolivia'), ('VE', 'Venezuela'), ('BR', 'Brasil'), ('PY', 'Paraguay'), ('UY', 'Uruguay'), ('US', 'Estados Unidos'), ('ES', 'España'), ('OT', 'Otro')], default='PE', max_length=2, verbose_name='País'),
        ),
        migrations.AddField(
            model_name='empresa',
            name='pais_otro',
            field=models.CharField(blank=True, help_text='Complete este campo si seleccionó "Otro" en País', max_length=100, null=True, verbose_name='Otro País (especificar)'),
        ),
        migrations.AddField(
            model_name='empresa',
            name='sector',
            field=models.CharField(blank=True, choices=[('tecnologia', 'Tecnología'), ('financiero', 'Financiero y Seguros'), ('manufactura', 'Manufactura'), ('retail', 'Retail y Comercio'), ('servicios', 'Servicios Profesionales'), ('salud', 'Salud y Farmacéutico'), ('educacion', 'Educación'), ('construccion', 'Construcción'), ('energia', 'Energía y Utilities'), ('telecomunicaciones', 'Telecomunicaciones'), ('agricultura', 'Agricultura y Ganadería'), ('mineria', 'Minería'), ('transporte', 'Transporte y Logística'), ('turismo', 'Turismo y Hospitalidad'), ('inmobiliario', 'Inmobiliario'), ('medios', 'Medios y Entretenimiento'), ('gobierno', 'Gobierno y Sector Público'), ('ong', 'ONG y Sin Fines de Lucro'), ('otro', 'Otro')], max_length=50, null=True, verbose_name='Sector o Rubro Empresarial'),
        ),
        migrations.AddField(
            model_name='empresa',
            name='sector_otro',
            field=models.CharField(blank=True, help_text='Complete este campo si seleccionó "Otro" en Sector', max_length=100, null=True, verbose_name='Otro Sector (especificar)'),
        ),
        migrations.AddField(
            model_name='empresa',
            name='tamanio',
            field=models.CharField(blank=True, choices=[('micro', 'Microempresa'), ('pequena', 'Pequeña Empresa'), ('mediana', 'Mediana Empresa'), ('grande', 'Gran Empresa'), ('otro', 'Otro')], max_length=20, null=True, verbose_name='Tamaño de Empresa'),
        ),
        migrations.AddField(
            model_name='empresa',
            name='tamanio_otro',
            field=models.CharField(blank=True, help_text='Complete este campo si seleccionó "Otro" en Tamaño', max_length=100, null=True, verbose_name='Otro Tamaño (especificar)'),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='ruc',
            field=models.CharField(blank=True, help_text='Número de identificación tributaria (RUC, RFC, NIT, etc.)', max_length=20, null=True, verbose_name='RUC / ID Fiscal'),
        ),
        migrations.AddIndex(
            model_name='empresa',
            index=models.Index(fields=['pais'], name='empresas_pais_4cceb5_idx'),
        ),
        migrations.AddIndex(
            model_name='empresa',
            index=models.Index(fields=['sector'], name='empresas_sector_76491f_idx'),
        ),
        migrations.AddIndex(
            model_name='empresa',
            index=models.Index(fields=['tamanio'], name='empresas_tamanio_163a0c_idx'),
        ),
    ]
