# Generated by Django 5.2.12 on 2026-03-31 00:39

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0002_empresa_pais_empresa_pais_otro_empresa_sector_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlanEmpresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, verbose_name='Fecha de Actualización')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('tipo', models.CharField(choices=[('demo', 'Demo'), ('basico', 'Básico'), ('profesional', 'Profesional'), ('enterprise', 'Enterprise')], default='demo', max_length=20, verbose_name='Tipo de Plan')),
                ('fecha_inicio', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de Inicio')),
                ('fecha_expiracion', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Expiración')),
                ('max_usuarios', models.PositiveIntegerField(default=3, verbose_name='Máx. Usuarios')),
                ('max_administradores', models.PositiveIntegerField(default=1, verbose_name='Máx. Administradores')),
                ('max_auditores', models.PositiveIntegerField(default=1, verbose_name='Máx. Auditores')),
                ('empresa', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='plan', to='empresas.empresa', verbose_name='Empresa')),
            ],
            options={
                'verbose_name': 'Plan de Empresa',
                'verbose_name_plural': 'Planes de Empresa',
                'db_table': 'planes_empresa',
            },
        ),
    ]
