# Generated by Django 5.0 on 2025-11-10 08:16

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('empresas', '0002_empresa_pais_empresa_pais_otro_empresa_sector_and_more'),
        ('encuestas', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Asignacion',
            fields=[
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, verbose_name='Fecha de Actualización')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('fecha_asignacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Asignación')),
                ('fecha_limite', models.DateField(verbose_name='Fecha Límite')),
                ('fecha_completado', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Completado')),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('en_progreso', 'En Progreso'), ('completado', 'Completado'), ('vencido', 'Vencido')], default='pendiente', max_length=20, verbose_name='Estado')),
                ('total_preguntas', models.IntegerField(default=0, verbose_name='Total de Preguntas')),
                ('preguntas_respondidas', models.IntegerField(default=0, verbose_name='Preguntas Respondidas')),
                ('porcentaje_avance', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Porcentaje de Avance')),
                ('observaciones', models.TextField(blank=True, verbose_name='Observaciones')),
                ('asignado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='asignaciones_creadas', to=settings.AUTH_USER_MODEL, verbose_name='Asignado Por')),
                ('dimension', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asignaciones', to='encuestas.dimension', verbose_name='Dimensión')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asignaciones', to='empresas.empresa', verbose_name='Empresa')),
                ('encuesta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asignaciones', to='encuestas.encuesta', verbose_name='Encuesta')),
                ('usuario_asignado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asignaciones', to=settings.AUTH_USER_MODEL, verbose_name='Usuario Asignado')),
            ],
            options={
                'verbose_name': 'Asignación',
                'verbose_name_plural': 'Asignaciones',
                'db_table': 'asignaciones',
                'ordering': ['-fecha_asignacion'],
                'indexes': [models.Index(fields=['usuario_asignado', 'estado'], name='asignacione_usuario_4f4bb4_idx'), models.Index(fields=['empresa', 'estado'], name='asignacione_empresa_8e09e3_idx'), models.Index(fields=['fecha_limite'], name='asignacione_fecha_l_e43331_idx')],
                'unique_together': {('dimension', 'usuario_asignado', 'empresa')},
            },
        ),
    ]
