# Generated by Django 5.0 on 2025-12-05 06:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asignaciones', '0001_initial'),
        ('empresas', '0002_empresa_pais_empresa_pais_otro_empresa_sector_and_more'),
        ('encuestas', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='asignacion',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='asignacion',
            name='asignado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='asignaciones_creadas', to=settings.AUTH_USER_MODEL, verbose_name='Asignado Por'),
        ),
        migrations.AlterField(
            model_name='asignacion',
            name='dimension',
            field=models.ForeignKey(blank=True, help_text='Si es NULL, la asignación es de la evaluación completa', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='asignaciones', to='encuestas.dimension', verbose_name='Dimensión'),
        ),
        migrations.AlterField(
            model_name='asignacion',
            name='observaciones',
            field=models.TextField(blank=True, default='', verbose_name='Observaciones'),
        ),
        migrations.AlterField(
            model_name='asignacion',
            name='usuario_asignado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asignaciones_recibidas', to=settings.AUTH_USER_MODEL, verbose_name='Usuario Asignado'),
        ),
        migrations.AddIndex(
            model_name='asignacion',
            index=models.Index(fields=['dimension'], name='asignacione_dimensi_444cb2_idx'),
        ),
        migrations.AddConstraint(
            model_name='asignacion',
            constraint=models.UniqueConstraint(condition=models.Q(('dimension__isnull', False)), fields=('encuesta', 'dimension', 'usuario_asignado'), name='unique_asignacion_dimension'),
        ),
        migrations.AddConstraint(
            model_name='asignacion',
            constraint=models.UniqueConstraint(condition=models.Q(('dimension__isnull', True)), fields=('encuesta', 'usuario_asignado'), name='unique_asignacion_evaluacion'),
        ),
    ]
