# Generated by Django 5.0 on 2025-12-14 06:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asignaciones', '0002_alter_asignacion_unique_together_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='asignacion',
            name='comentarios_revision',
            field=models.TextField(blank=True, default='', help_text='Observaciones del revisor al aprobar o rechazar', verbose_name='Comentarios de Revisión'),
        ),
        migrations.AddField(
            model_name='asignacion',
            name='fecha_envio_revision',
            field=models.DateTimeField(blank=True, help_text='Fecha en que el usuario envió para revisión', null=True, verbose_name='Fecha Envío a Revisión'),
        ),
        migrations.AddField(
            model_name='asignacion',
            name='fecha_revision',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Revisión'),
        ),
        migrations.AddField(
            model_name='asignacion',
            name='requiere_revision',
            field=models.BooleanField(default=False, help_text='Si TRUE, el administrador debe revisar antes de marcar como completado', verbose_name='Requiere Revisión'),
        ),
        migrations.AddField(
            model_name='asignacion',
            name='revisado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='asignaciones_revisadas', to=settings.AUTH_USER_MODEL, verbose_name='Revisado Por'),
        ),
        migrations.AlterField(
            model_name='asignacion',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('en_progreso', 'En Progreso'), ('completado', 'Completado'), ('vencido', 'Vencido'), ('pendiente_revision', 'Pendiente de Revisión'), ('rechazado', 'Rechazado')], default='pendiente', max_length=20, verbose_name='Estado'),
        ),
    ]
