# Generated by Django 5.0 on 2025-12-28 19:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('asignaciones', '0003_asignacion_comentarios_revision_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='asignacion',
            name='unique_asignacion_dimension',
        ),
        migrations.RemoveConstraint(
            model_name='asignacion',
            name='unique_asignacion_evaluacion',
        ),
    ]
