# Generated by Django 5.0 on 2025-12-28 19:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asignaciones', '0004_remove_asignacion_unique_asignacion_dimension_and_more'),
        ('empresas', '0002_empresa_pais_empresa_pais_otro_empresa_sector_and_more'),
        ('encuestas', '0002_evaluacionempresa_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='asignacion',
            name='evaluacion_empresa',
            field=models.ForeignKey(blank=True, help_text='Evaluación específica a la que pertenece esta asignación', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='asignaciones', to='encuestas.evaluacionempresa', verbose_name='Evaluación Empresa'),
        ),
        migrations.AlterField(
            model_name='asignacion',
            name='dimension',
            field=models.ForeignKey(blank=True, help_text='Dimensión asignada (NULL si es evaluación completa)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='asignaciones', to='encuestas.dimension', verbose_name='Dimensión'),
        ),
        migrations.AlterField(
            model_name='asignacion',
            name='empresa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asignaciones_directas', to='empresas.empresa', verbose_name='Empresa'),
        ),
        migrations.AlterField(
            model_name='asignacion',
            name='encuesta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asignaciones_directas', to='encuestas.encuesta', verbose_name='Encuesta'),
        ),
        migrations.AddIndex(
            model_name='asignacion',
            index=models.Index(fields=['evaluacion_empresa', 'estado'], name='asignacione_evaluac_dab59a_idx'),
        ),
        migrations.AddConstraint(
            model_name='asignacion',
            constraint=models.UniqueConstraint(condition=models.Q(('activo', True), ('dimension__isnull', False)), fields=('evaluacion_empresa', 'dimension', 'usuario_asignado'), name='unique_asignacion_evaluacion_dimension_usuario'),
        ),
    ]
