# Generated by Django 5.0 on 2026-02-26 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asignaciones', '0005_asignacion_evaluacion_empresa_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asignacion',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('en_progreso', 'En Progreso'), ('completado', 'Completado'), ('vencido', 'Vencido'), ('pendiente_revision', 'Pendiente de Revisión'), ('pendiente_auditoria', 'Pendiente de Auditoría'), ('rechazado', 'Rechazado')], default='pendiente', max_length=20, verbose_name='Estado'),
        ),
    ]
