# Generated by Django 5.0 on 2026-01-21 22:18

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, verbose_name='Fecha de Actualización')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('razon_social', models.CharField(max_length=200, verbose_name='Razón Social')),
                ('ruc', models.CharField(max_length=20, unique=True, verbose_name='RUC/Tax ID')),
                ('tipo_proveedor', models.CharField(choices=[('consultoria', 'Consultoría CMMI/GRC'), ('software', 'Software/Herramientas'), ('capacitacion', 'Capacitación y Entrenamiento'), ('auditoria', 'Auditoría y Certificación'), ('infraestructura', 'Infraestructura TI'), ('otro', 'Otro')], max_length=50, verbose_name='Tipo de Proveedor')),
                ('contacto_email', models.EmailField(max_length=254, verbose_name='Email de Contacto')),
                ('contacto_telefono', models.CharField(max_length=20, verbose_name='Teléfono')),
                ('creado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='proveedores_creados', to=settings.AUTH_USER_MODEL, verbose_name='Creado Por')),
            ],
            options={
                'verbose_name': 'Proveedor',
                'verbose_name_plural': 'Proveedores',
                'db_table': 'proveedores',
                'ordering': ['-fecha_creacion'],
                'indexes': [models.Index(fields=['ruc'], name='proveedores_ruc_a5d69c_idx'), models.Index(fields=['tipo_proveedor'], name='proveedores_tipo_pr_68a632_idx'), models.Index(fields=['activo'], name='proveedores_activo_068092_idx')],
            },
        ),
    ]
