# Generated by Django 5.0 on 2026-02-02 06:31

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('empresas', '0002_empresa_pais_empresa_pais_otro_empresa_sector_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ClasificacionProveedor',
            fields=[
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, verbose_name='Fecha de Actualización')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('codigo', models.CharField(choices=[('estrategico', 'Proveedor Estratégico'), ('critico', 'Proveedor Crítico'), ('no_critico', 'Proveedor No Crítico'), ('temporal', 'Proveedor Temporal')], max_length=50, unique=True, verbose_name='Código')),
                ('nombre', models.CharField(max_length=200, verbose_name='Nombre')),
                ('descripcion', models.TextField(blank=True, null=True, verbose_name='Descripción')),
                ('color', models.CharField(default='#6B7280', help_text='Color en formato hexadecimal para UI', max_length=7, verbose_name='Color (Hex)')),
            ],
            options={
                'verbose_name': 'Clasificación de Proveedor',
                'verbose_name_plural': 'Clasificaciones de Proveedor',
                'db_table': 'clasificaciones_proveedor',
                'ordering': ['codigo'],
                'indexes': [models.Index(fields=['codigo'], name='clasificaci_codigo_f5eb98_idx'), models.Index(fields=['activo'], name='clasificaci_activo_67fafb_idx')],
            },
        ),
        migrations.CreateModel(
            name='TipoProveedor',
            fields=[
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, verbose_name='Fecha de Actualización')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=200, unique=True, verbose_name='Nombre del Tipo')),
                ('descripcion', models.TextField(blank=True, null=True, verbose_name='Descripción')),
                ('orden', models.IntegerField(default=0, help_text='Orden alfabético o de prioridad', verbose_name='Orden')),
            ],
            options={
                'verbose_name': 'Tipo de Proveedor',
                'verbose_name_plural': 'Tipos de Proveedor',
                'db_table': 'tipos_proveedor',
                'ordering': ['orden', 'nombre'],
                'indexes': [models.Index(fields=['nombre'], name='tipos_prove_nombre_97e63c_idx'), models.Index(fields=['activo'], name='tipos_prove_activo_e6f593_idx')],
            },
        ),
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, verbose_name='Fecha de Actualización')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('razon_social', models.CharField(max_length=200, verbose_name='Razón Social')),
                ('nombre_comercial', models.CharField(blank=True, max_length=200, null=True, verbose_name='Nombre Comercial')),
                ('pais', models.CharField(default='Perú', max_length=100, verbose_name='País')),
                ('tipo_documento_fiscal', models.CharField(default='RUC', help_text='RUC, Tax ID, NIT, etc.', max_length=50, verbose_name='Tipo de Documento Fiscal')),
                ('numero_documento_fiscal', models.CharField(max_length=50, verbose_name='Número de Documento Fiscal')),
                ('direccion_legal', models.TextField(blank=True, null=True, verbose_name='Dirección Legal')),
                ('nombre_contacto_principal', models.CharField(blank=True, max_length=200, null=True, verbose_name='Nombre del Contacto Principal')),
                ('cargo_contacto', models.CharField(blank=True, max_length=100, null=True, verbose_name='Cargo del Contacto')),
                ('email_contacto', models.EmailField(max_length=254, verbose_name='Email de Contacto')),
                ('telefono_contacto', models.CharField(max_length=20, verbose_name='Teléfono de Contacto')),
                ('numero_contrato', models.CharField(blank=True, max_length=100, null=True, verbose_name='Número de Contrato')),
                ('fecha_inicio_contrato', models.DateField(blank=True, null=True, verbose_name='Fecha de Inicio del Contrato')),
                ('fecha_fin_contrato', models.DateField(blank=True, null=True, verbose_name='Fecha de Fin del Contrato')),
                ('tipo_contrato', models.CharField(blank=True, choices=[('servicio', 'Contrato de Servicios'), ('compra', 'Contrato de Compra'), ('licencia', 'Licenciamiento'), ('outsourcing', 'Outsourcing'), ('consultoria', 'Consultoría'), ('mantenimiento', 'Mantenimiento'), ('otro', 'Otro')], max_length=50, null=True, verbose_name='Tipo de Contrato')),
                ('sla_aplica', models.BooleanField(default=False, verbose_name='¿Aplica SLA?')),
                ('nivel_riesgo', models.CharField(choices=[('alto', 'Alto'), ('medio', 'Medio'), ('bajo', 'Bajo')], default='medio', max_length=20, verbose_name='Nivel de Riesgo')),
                ('proveedor_estrategico', models.BooleanField(default=False, verbose_name='¿Es Proveedor Estratégico?')),
                ('estado_proveedor', models.CharField(choices=[('activo', 'Activo'), ('inactivo', 'Inactivo'), ('suspendido', 'Suspendido')], default='activo', max_length=20, verbose_name='Estado del Proveedor')),
                ('fecha_alta', models.DateField(auto_now_add=True, verbose_name='Fecha de Alta')),
                ('fecha_baja', models.DateField(blank=True, null=True, verbose_name='Fecha de Baja')),
                ('requiere_certificaciones', models.BooleanField(default=False, verbose_name='¿Requiere Certificaciones?')),
                ('certificaciones', models.JSONField(blank=True, default=list, help_text='Lista de certificaciones: ISO 9001, ISO 27001, SOC 2, etc.', verbose_name='Certificaciones')),
                ('cumple_compliance', models.BooleanField(default=True, verbose_name='¿Cumple Compliance?')),
                ('ultima_evaluacion_riesgo', models.DateField(blank=True, null=True, verbose_name='Última Evaluación de Riesgo')),
                ('proxima_evaluacion_riesgo', models.DateField(blank=True, null=True, verbose_name='Próxima Evaluación de Riesgo')),
                ('observaciones', models.TextField(blank=True, null=True, verbose_name='Observaciones')),
                ('clasificacion', models.ForeignKey(blank=True, help_text='Clasificación de criticidad del proveedor', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='proveedores', to='proveedores.clasificacionproveedor', verbose_name='Clasificación')),
                ('creado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='proveedores_creados', to=settings.AUTH_USER_MODEL, verbose_name='Creado Por')),
                ('empresa', models.ForeignKey(blank=True, help_text='Si está vacío, es un proveedor global (solo superadmin)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='proveedores', to='empresas.empresa', verbose_name='Empresa')),
                ('tipo_proveedor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='proveedores', to='proveedores.tipoproveedor', verbose_name='Tipo de Proveedor')),
            ],
            options={
                'verbose_name': 'Proveedor',
                'verbose_name_plural': 'Proveedores',
                'db_table': 'proveedores',
                'ordering': ['-fecha_creacion'],
                'indexes': [models.Index(fields=['numero_documento_fiscal'], name='proveedores_numero__1676ce_idx'), models.Index(fields=['tipo_proveedor'], name='proveedores_tipo_pr_ea695d_idx'), models.Index(fields=['clasificacion'], name='proveedores_clasifi_3ef8c2_idx'), models.Index(fields=['activo'], name='proveedores_activo_068092_idx'), models.Index(fields=['empresa'], name='proveedores_empresa_843a7b_idx'), models.Index(fields=['nivel_riesgo'], name='proveedores_nivel_r_c0353d_idx'), models.Index(fields=['estado_proveedor'], name='proveedores_estado__e5f712_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='proveedor',
            constraint=models.UniqueConstraint(fields=('numero_documento_fiscal', 'empresa'), name='unique_documento_fiscal_por_empresa'),
        ),
    ]
