# Generated by Django 5.0 on 2026-01-23 19:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0002_empresa_pais_empresa_pais_otro_empresa_sector_and_more'),
        ('proveedores', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='proveedor',
            name='empresa',
            field=models.ForeignKey(blank=True, help_text='Si está vacío, es un proveedor global (solo superadmin)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='proveedores', to='empresas.empresa', verbose_name='Empresa'),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='ruc',
            field=models.CharField(max_length=20, verbose_name='RUC/Tax ID'),
        ),
        migrations.AddIndex(
            model_name='proveedor',
            index=models.Index(fields=['empresa'], name='proveedores_empresa_843a7b_idx'),
        ),
        migrations.AddConstraint(
            model_name='proveedor',
            constraint=models.UniqueConstraint(fields=('ruc', 'empresa'), name='unique_ruc_por_empresa'),
        ),
    ]
