# Generated by Django 5.0 on 2026-01-15 05:08

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('empresas', '0002_empresa_pais_empresa_pais_otro_empresa_sector_and_more'),
        ('encuestas', '0002_evaluacionempresa_and_more'),
        ('respuestas', '0006_alter_evidencia_archivo_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProyectoCierreBrecha',
            fields=[
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, verbose_name='Fecha de Actualización')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID del Proyecto')),
                ('codigo_proyecto', models.CharField(db_index=True, help_text='Código único autogenerado (ej: REM-2025-001)', max_length=50, unique=True, verbose_name='Código del Proyecto')),
                ('nombre_proyecto', models.CharField(help_text='Nombre descriptivo del proyecto', max_length=200, verbose_name='Nombre del Proyecto de Remediación')),
                ('descripcion', models.TextField(help_text='Descripción detallada del alcance y objetivos', max_length=1000, verbose_name='Descripción del Proyecto')),
                ('fecha_inicio', models.DateField(verbose_name='Fecha de Inicio del Proyecto')),
                ('fecha_fin_estimada', models.DateField(verbose_name='Fecha de Finalización Estimada')),
                ('fecha_fin_real', models.DateField(blank=True, null=True, verbose_name='Fecha de Finalización Real')),
                ('estado', models.CharField(choices=[('planificado', 'Planificado'), ('en_ejecucion', 'En Ejecución'), ('en_validacion', 'En Validación'), ('cerrado', 'Cerrado'), ('suspendido', 'Suspendido'), ('cancelado', 'Cancelado')], default='planificado', max_length=20, verbose_name='Estado del Proyecto')),
                ('prioridad', models.CharField(choices=[('critica', 'Crítica'), ('alta', 'Alta'), ('media', 'Media'), ('baja', 'Baja')], help_text='Derivada de la criticidad del GAP', max_length=20, verbose_name='Prioridad del Proyecto')),
                ('categoria', models.CharField(choices=[('tecnico', 'Técnico'), ('documental', 'Documental'), ('procesal', 'Procesal'), ('organizacional', 'Organizacional'), ('capacitacion', 'Capacitación')], max_length=20, verbose_name='Categoría de Proyecto')),
                ('normativa', models.CharField(choices=[('iso_27001', 'ISO 27001'), ('iso_9001', 'ISO 9001'), ('nist_csf', 'NIST CSF'), ('gdpr', 'GDPR'), ('pci_dss', 'PCI-DSS'), ('sox', 'SOX'), ('hipaa', 'HIPAA'), ('cmmi', 'CMMI'), ('otro', 'Otro')], help_text='Marco normativo de cumplimiento', max_length=20, verbose_name='Normativa/Estándar')),
                ('control_no_conforme', models.CharField(help_text='Código y descripción del control que no cumple', max_length=200, verbose_name='Control/Requisito No Conforme')),
                ('tipo_brecha', models.CharField(choices=[('ausencia_total', 'Ausencia Total'), ('parcial', 'Parcial'), ('no_efectiva', 'No Efectiva'), ('no_documentada', 'No Documentada')], help_text='Clasificación de la no conformidad', max_length=20, verbose_name='Tipo de Brecha')),
                ('nivel_criticidad_original', models.IntegerField(help_text='Criticidad identificada en el análisis GAP', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Nivel de Criticidad Original (1-5)')),
                ('impacto_riesgo', models.TextField(help_text='Descripción del impacto si no se remedia', verbose_name='Impacto Estimado del Riesgo')),
                ('evidencia_no_conformidad', models.CharField(blank=True, help_text='Ruta o URL de la evidencia del GAP', max_length=500, verbose_name='Evidencia de No Conformidad Original')),
                ('fecha_identificacion_gap', models.DateField(help_text='Fecha en que se identificó la brecha', verbose_name='Fecha de Identificación (GAP)')),
                ('estrategia_cierre', models.CharField(choices=[('implementacion_nueva', 'Implementación Nueva'), ('fortalecimiento', 'Fortalecimiento'), ('optimizacion', 'Optimización'), ('documentacion', 'Documentación')], help_text='Enfoque para cerrar la brecha', max_length=30, verbose_name='Estrategia de Cierre Seleccionada')),
                ('alcance_proyecto', models.TextField(help_text='Qué se incluye y qué no en el proyecto', verbose_name='Alcance del Proyecto')),
                ('objetivos_especificos', models.TextField(help_text='Lista de objetivos medibles y verificables', verbose_name='Objetivos de Cierre Específicos')),
                ('criterios_aceptacion', models.TextField(help_text='Condiciones que deben cumplirse para dar por cerrado el proyecto', verbose_name='Criterios de Aceptación')),
                ('supuestos', models.TextField(blank=True, help_text='Condiciones que se asumen como verdaderas', verbose_name='Supuestos del Proyecto')),
                ('restricciones', models.TextField(blank=True, help_text='Limitaciones del proyecto (tiempo, presupuesto, recursos)', verbose_name='Restricciones Identificadas')),
                ('riesgos_proyecto', models.TextField(blank=True, help_text='Riesgos identificados que podrían afectar el proyecto', verbose_name='Riesgos del Proyecto de Cierre')),
                ('presupuesto_asignado', models.DecimalField(decimal_places=2, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Presupuesto Asignado')),
                ('moneda', models.CharField(choices=[('USD', 'USD - Dólar Estadounidense'), ('EUR', 'EUR - Euro'), ('GBP', 'GBP - Libra Esterlina'), ('PEN', 'PEN - Sol Peruano'), ('COP', 'COP - Peso Colombiano'), ('MXN', 'MXN - Peso Mexicano'), ('CLP', 'CLP - Peso Chileno'), ('ARS', 'ARS - Peso Argentino')], default='USD', max_length=3, verbose_name='Moneda del Presupuesto')),
                ('presupuesto_gastado', models.DecimalField(decimal_places=2, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Presupuesto Gastado')),
                ('recursos_humanos_asignados', models.DecimalField(decimal_places=2, default=0, help_text='Horas-persona estimadas', max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Recursos Humanos Asignados (Horas)')),
                ('recursos_tecnicos', models.TextField(blank=True, help_text='Hardware, software, herramientas necesarias', verbose_name='Recursos Técnicos Requeridos')),
                ('frecuencia_reporte', models.CharField(choices=[('diaria', 'Diaria'), ('semanal', 'Semanal'), ('quincenal', 'Quincenal'), ('mensual', 'Mensual')], default='semanal', help_text='Periodicidad de reportes de avance', max_length=20, verbose_name='Frecuencia de Reporte')),
                ('metricas_desempeno', models.TextField(blank=True, help_text='KPIs para medir el desempeño', verbose_name='Métricas de Desempeño del Proyecto')),
                ('umbrales_alerta', models.TextField(blank=True, help_text='Ejemplo: Retraso >10% genera alerta amarilla', verbose_name='Umbrales de Alerta')),
                ('canal_comunicacion', models.CharField(choices=[('email', 'Email'), ('teams', 'Microsoft Teams'), ('slack', 'Slack'), ('whatsapp', 'WhatsApp'), ('otro', 'Otro')], default='email', max_length=20, verbose_name='Canal de Comunicación Principal')),
                ('criterios_validacion', models.TextField(help_text='Criterios que debe cumplir para ser validado', verbose_name='Criterios de Validación Específicos')),
                ('metodo_verificacion', models.CharField(choices=[('muestreo', 'Muestreo'), ('prueba_completa', 'Prueba Completa'), ('observacion', 'Observación'), ('revision_documental', 'Revisión Documental'), ('entrevista', 'Entrevista'), ('inspeccion', 'Inspección Física')], help_text='Cómo se verificará el cumplimiento', max_length=30, verbose_name='Método de Verificación')),
                ('fecha_cierre_tecnico', models.DateField(blank=True, help_text='Cuando se completó la implementación técnica', null=True, verbose_name='Fecha de Cierre Técnico')),
                ('fecha_cierre_formal', models.DateField(blank=True, help_text='Cuando se validó formalmente el cierre', null=True, verbose_name='Fecha de Cierre Formal')),
                ('resultado_final', models.CharField(blank=True, choices=[('exitoso', 'Exitoso'), ('parcialmente_exitoso', 'Parcialmente Exitoso'), ('no_exitoso', 'No Exitoso'), ('cancelado', 'Cancelado')], max_length=30, verbose_name='Resultado Final')),
                ('lecciones_aprendidas', models.TextField(blank=True, help_text='Qué funcionó bien y qué se puede mejorar', verbose_name='Lecciones Aprendidas')),
                ('acciones_mejora_continua', models.TextField(blank=True, help_text='Mejoras identificadas para futuros proyectos', verbose_name='Acciones de Mejora Continua Derivadas')),
                ('recomendaciones_futuros_gap', models.TextField(blank=True, help_text='Feedback para mejorar próximos análisis GAP', verbose_name='Recomendaciones para Futuros Análisis GAP')),
                ('version', models.IntegerField(default=1, help_text='Se incrementa con cada modificación mayor', verbose_name='Versión del Proyecto')),
                ('auditor_verificacion', models.ForeignKey(blank=True, help_text='Quien valida el cierre formal del proyecto', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='proyectos_auditor', to=settings.AUTH_USER_MODEL, verbose_name='Auditor de Verificación')),
                ('calculo_nivel', models.ForeignKey(help_text='CalculoNivel que originó este proyecto', on_delete=django.db.models.deletion.PROTECT, related_name='proyectos_remediacion', to='respuestas.calculonivel', verbose_name='Brecha GAP Asociada')),
                ('creado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='proyectos_remediacion_creados', to=settings.AUTH_USER_MODEL, verbose_name='Creado Por')),
                ('dueno_proyecto', models.ForeignKey(help_text='Responsable general del éxito del proyecto', on_delete=django.db.models.deletion.PROTECT, related_name='proyectos_propietario', to=settings.AUTH_USER_MODEL, verbose_name='Dueño del Proyecto (Project Owner)')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proyectos_remediacion', to='empresas.empresa', verbose_name='Empresa')),
                ('equipo_implementacion', models.ManyToManyField(blank=True, help_text='Miembros del equipo que ejecutarán tareas', related_name='proyectos_equipo', to=settings.AUTH_USER_MODEL, verbose_name='Equipo de Implementación')),
                ('preguntas_abordadas', models.ManyToManyField(blank=True, help_text='Preguntas específicas del GAP que este proyecto remedia', related_name='proyectos_remediacion', to='encuestas.pregunta', verbose_name='Preguntas Abordadas')),
                ('responsable_implementacion', models.ForeignKey(help_text='Quien ejecuta las tareas técnicas (R en RACI)', on_delete=django.db.models.deletion.PROTECT, related_name='proyectos_responsable', to=settings.AUTH_USER_MODEL, verbose_name='Responsable de Implementación')),
                ('responsable_validacion', models.ForeignKey(blank=True, help_text='Quien valida que se cumplieron los criterios', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='proyectos_validacion', to=settings.AUTH_USER_MODEL, verbose_name='Responsable de Validación')),
                ('validador_interno', models.ForeignKey(blank=True, help_text='Quien aprueba los entregables (A en RACI)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='proyectos_validador', to=settings.AUTH_USER_MODEL, verbose_name='Validador/Aprobador Interno')),
            ],
            options={
                'verbose_name': 'Proyecto de Cierre de Brecha',
                'verbose_name_plural': 'Proyectos de Cierre de Brecha',
                'db_table': 'proyectos_cierre_brecha',
                'ordering': ['-fecha_creacion'],
                'indexes': [models.Index(fields=['empresa', 'estado'], name='proyectos_c_empresa_94fb0e_idx'), models.Index(fields=['codigo_proyecto'], name='proyectos_c_codigo__deed3a_idx'), models.Index(fields=['prioridad'], name='proyectos_c_priorid_6cfac4_idx'), models.Index(fields=['calculo_nivel'], name='proyectos_c_calculo_095929_idx'), models.Index(fields=['fecha_inicio'], name='proyectos_c_fecha_i_4c4135_idx'), models.Index(fields=['fecha_fin_estimada'], name='proyectos_c_fecha_f_25ba5a_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='proyectocierrebrecha',
            constraint=models.UniqueConstraint(fields=('codigo_proyecto',), name='unique_codigo_proyecto'),
        ),
    ]
