# Generated by Django 5.0 on 2026-02-02 06:33

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('empresas', '0002_empresa_pais_empresa_pais_otro_empresa_sector_and_more'),
        ('encuestas', '0002_evaluacionempresa_and_more'),
        ('proveedores', '0001_initial'),
        ('respuestas', '0007_delete_iniciativa'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProyectoCierreBrecha',
            fields=[
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, verbose_name='Fecha de Actualización')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID del Proyecto')),
                ('codigo_proyecto', models.CharField(db_index=True, help_text='Código único autogenerado (ej: REM-2025-001)', max_length=50, unique=True, verbose_name='Código del Proyecto')),
                ('nombre_proyecto', models.CharField(max_length=200, verbose_name='Nombre del Proyecto')),
                ('descripcion', models.TextField(max_length=1000, verbose_name='Descripción del Proyecto')),
                ('estado', models.CharField(choices=[('planificado', 'Planificado'), ('en_ejecucion', 'En Ejecución'), ('en_validacion', 'En Validación'), ('cerrado', 'Cerrado'), ('suspendido', 'Suspendido'), ('cancelado', 'Cancelado')], default='planificado', max_length=20, verbose_name='Estado del Proyecto')),
                ('prioridad', models.CharField(choices=[('critica', 'Crítica'), ('alta', 'Alta'), ('media', 'Media'), ('baja', 'Baja')], help_text='Derivada de la criticidad del GAP', max_length=20, verbose_name='Prioridad')),
                ('categoria', models.CharField(choices=[('tecnico', 'Técnico'), ('documental', 'Documental'), ('procesal', 'Procesal'), ('organizacional', 'Organizacional'), ('capacitacion', 'Capacitación')], max_length=20, verbose_name='Categoría de Proyecto')),
                ('fecha_inicio', models.DateField(verbose_name='Fecha de Inicio')),
                ('fecha_fin_estimada', models.DateField(verbose_name='Fecha de Fin Estimada')),
                ('fecha_fin_real', models.DateField(blank=True, null=True, verbose_name='Fecha de Fin Real')),
                ('modo_presupuesto', models.CharField(choices=[('global', 'Presupuesto Global'), ('por_items', 'Presupuesto por Ítems')], default='global', help_text='Global: monto único. Por ítems: suma de ítems individuales', max_length=20, verbose_name='Modo de Presupuesto')),
                ('moneda', models.CharField(choices=[('USD', 'USD - Dólar Estadounidense'), ('EUR', 'EUR - Euro'), ('PEN', 'PEN - Sol Peruano'), ('COP', 'COP - Peso Colombiano'), ('MXN', 'MXN - Peso Mexicano')], default='USD', max_length=3, verbose_name='Moneda')),
                ('presupuesto_global', models.DecimalField(decimal_places=2, default=0, help_text='Solo aplica si modo_presupuesto = "global"', max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Presupuesto Global')),
                ('presupuesto_global_gastado', models.DecimalField(decimal_places=2, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Presupuesto Global Gastado')),
                ('alcance_proyecto', models.TextField(help_text='Qué se incluye y qué no', verbose_name='Alcance del Proyecto')),
                ('objetivos_especificos', models.TextField(help_text='Lista de objetivos medibles', verbose_name='Objetivos Específicos')),
                ('criterios_aceptacion', models.TextField(help_text='Condiciones para dar por cerrado el proyecto', verbose_name='Criterios de Aceptación')),
                ('riesgos_proyecto', models.TextField(blank=True, help_text='Riesgos que podrían afectar el proyecto', verbose_name='Riesgos Identificados')),
                ('resultado_final', models.CharField(blank=True, choices=[('exitoso', 'Exitoso'), ('parcialmente_exitoso', 'Parcialmente Exitoso'), ('no_exitoso', 'No Exitoso'), ('cancelado', 'Cancelado')], max_length=30, verbose_name='Resultado Final')),
                ('lecciones_aprendidas', models.TextField(blank=True, verbose_name='Lecciones Aprendidas')),
                ('version', models.IntegerField(default=1, verbose_name='Versión del Proyecto')),
                ('calculo_nivel', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='proyectos_remediacion', to='respuestas.calculonivel', verbose_name='Brecha GAP Asociada')),
                ('creado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='proyectos_remediacion_creados', to=settings.AUTH_USER_MODEL, verbose_name='Creado Por')),
                ('dueno_proyecto', models.ForeignKey(help_text='Responsable general del proyecto', on_delete=django.db.models.deletion.PROTECT, related_name='proyectos_propietario', to=settings.AUTH_USER_MODEL, verbose_name='Dueño del Proyecto')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proyectos_remediacion', to='empresas.empresa', verbose_name='Empresa')),
                ('preguntas_abordadas', models.ManyToManyField(blank=True, related_name='proyectos_remediacion', to='encuestas.pregunta', verbose_name='Preguntas Abordadas')),
                ('responsable_implementacion', models.ForeignKey(help_text='Quien ejecuta las tareas', on_delete=django.db.models.deletion.PROTECT, related_name='proyectos_responsable', to=settings.AUTH_USER_MODEL, verbose_name='Responsable de Implementación')),
                ('validador_interno', models.ForeignKey(blank=True, help_text='Quien aprueba el proyecto', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='proyectos_validador', to=settings.AUTH_USER_MODEL, verbose_name='Validador Interno')),
            ],
            options={
                'verbose_name': 'Proyecto de Cierre de Brecha',
                'verbose_name_plural': 'Proyectos de Cierre de Brecha',
                'db_table': 'proyectos_cierre_brecha',
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='ItemProyecto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, verbose_name='Fecha de Actualización')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('numero_item', models.IntegerField(help_text='Orden secuencial (1, 2, 3...)', verbose_name='Número de Ítem')),
                ('nombre_item', models.CharField(help_text='Ej: Adquisición de Licencia de Antivirus', max_length=200, verbose_name='Nombre del Ítem')),
                ('descripcion', models.TextField(blank=True, verbose_name='Descripción')),
                ('requiere_proveedor', models.BooleanField(default=False, verbose_name='¿Requiere Proveedor?')),
                ('nombre_responsable_proveedor', models.CharField(blank=True, help_text='Ej: Responsable de Compras, Gerente Comercial', max_length=150, verbose_name='Responsable del Proveedor')),
                ('presupuesto_planificado', models.DecimalField(decimal_places=2, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Presupuesto Planificado')),
                ('presupuesto_ejecutado', models.DecimalField(decimal_places=2, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Presupuesto Ejecutado')),
                ('fecha_inicio', models.DateField(verbose_name='Fecha de Inicio')),
                ('duracion_dias', models.IntegerField(help_text='Días que tomará este ítem', validators=[django.core.validators.MinValueValidator(1)], verbose_name='Duración en Días')),
                ('fecha_fin', models.DateField(help_text='Se calcula: fecha_inicio + duracion_dias', verbose_name='Fecha de Fin (Calculada)')),
                ('tiene_dependencia', models.BooleanField(default=False, help_text='Si depende de otro ítem para iniciar', verbose_name='¿Tiene Dependencia?')),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('en_proceso', 'En Proceso'), ('completado', 'Completado'), ('bloqueado', 'Bloqueado por Dependencia')], default='pendiente', max_length=20, verbose_name='Estado del Ítem')),
                ('porcentaje_avance', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Avance (%)')),
                ('fecha_completado', models.DateField(blank=True, help_text='Fecha en que el ítem fue marcado como completado', null=True, verbose_name='Fecha de Completado')),
                ('observaciones', models.TextField(blank=True, verbose_name='Observaciones')),
                ('item_dependencia', models.ForeignKey(blank=True, help_text='Solo si tiene_dependencia=True', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='items_dependientes', to='proyectos_remediacion.itemproyecto', verbose_name='Ítem del que Depende')),
                ('proveedor', models.ForeignKey(blank=True, help_text='Solo si requiere_proveedor=True', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='items_proyecto', to='proveedores.proveedor', verbose_name='Proveedor')),
                ('responsable_ejecucion', models.ForeignKey(help_text='Quien ejecuta este ítem (Obligatorio)', on_delete=django.db.models.deletion.PROTECT, related_name='items_responsable', to=settings.AUTH_USER_MODEL, verbose_name='Responsable de Ejecución')),
                ('proyecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='proyectos_remediacion.proyectocierrebrecha', verbose_name='Proyecto')),
            ],
            options={
                'verbose_name': 'Ítem de Proyecto',
                'verbose_name_plural': 'Ítems de Proyecto',
                'ordering': ['proyecto', 'numero_item'],
            },
        ),
        migrations.CreateModel(
            name='AprobacionGAP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, verbose_name='Fecha de Actualización')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('fecha_solicitud', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de solicitud')),
                ('comentarios_solicitud', models.TextField(blank=True, help_text='Comentarios del responsable al solicitar la aprobación', verbose_name='Comentarios de la solicitud')),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('aprobado', 'Aprobado'), ('rechazado', 'Rechazado')], default='pendiente', max_length=20, verbose_name='Estado')),
                ('fecha_revision', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de revisión')),
                ('observaciones', models.TextField(blank=True, help_text='Observaciones del validador (requerido si rechaza)', verbose_name='Observaciones')),
                ('documentos_adjuntos', models.JSONField(blank=True, default=list, help_text='Lista de URLs de documentos de evidencia', verbose_name='Documentos adjuntos')),
                ('items_completados', models.IntegerField(default=0, verbose_name='Ítems completados')),
                ('items_totales', models.IntegerField(default=0, verbose_name='Ítems totales')),
                ('presupuesto_ejecutado', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Presupuesto ejecutado')),
                ('presupuesto_planificado', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Presupuesto planificado')),
                ('gap_original', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='GAP original')),
                ('solicitado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='aprobaciones_solicitadas', to=settings.AUTH_USER_MODEL, verbose_name='Solicitado por')),
                ('validador', models.ForeignKey(help_text='Usuario que debe aprobar o rechazar', on_delete=django.db.models.deletion.PROTECT, related_name='aprobaciones_asignadas', to=settings.AUTH_USER_MODEL, verbose_name='Validador')),
                ('proyecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aprobaciones', to='proyectos_remediacion.proyectocierrebrecha', verbose_name='Proyecto')),
            ],
            options={
                'verbose_name': 'Aprobación de GAP',
                'verbose_name_plural': 'Aprobaciones de GAP',
                'ordering': ['-fecha_solicitud'],
            },
        ),
        migrations.AddIndex(
            model_name='proyectocierrebrecha',
            index=models.Index(fields=['empresa', 'estado'], name='proyectos_c_empresa_94fb0e_idx'),
        ),
        migrations.AddIndex(
            model_name='proyectocierrebrecha',
            index=models.Index(fields=['codigo_proyecto'], name='proyectos_c_codigo__deed3a_idx'),
        ),
        migrations.AddIndex(
            model_name='proyectocierrebrecha',
            index=models.Index(fields=['prioridad'], name='proyectos_c_priorid_6cfac4_idx'),
        ),
        migrations.AddIndex(
            model_name='proyectocierrebrecha',
            index=models.Index(fields=['calculo_nivel'], name='proyectos_c_calculo_095929_idx'),
        ),
        migrations.AddConstraint(
            model_name='proyectocierrebrecha',
            constraint=models.UniqueConstraint(fields=('codigo_proyecto',), name='unique_codigo_proyecto'),
        ),
        migrations.AddConstraint(
            model_name='itemproyecto',
            constraint=models.UniqueConstraint(fields=('proyecto', 'numero_item'), name='unique_numero_item_por_proyecto'),
        ),
        migrations.AddIndex(
            model_name='aprobaciongap',
            index=models.Index(fields=['estado', 'fecha_solicitud'], name='proyectos_r_estado_499703_idx'),
        ),
        migrations.AddIndex(
            model_name='aprobaciongap',
            index=models.Index(fields=['validador', 'estado'], name='proyectos_r_validad_b9789b_idx'),
        ),
    ]
