# Generated by Django 5.0 on 2026-01-22 20:23

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('encuestas', '0002_evaluacionempresa_and_more'),
        ('proveedores', '0001_initial'),
        ('proyectos_remediacion', '0001_initial'),
        ('respuestas', '0007_delete_iniciativa'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemProyecto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, verbose_name='Fecha de Actualización')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('numero_item', models.IntegerField(help_text='Orden secuencial (1, 2, 3...)', verbose_name='Número de Ítem')),
                ('nombre_item', models.CharField(help_text='Ej: Adquisición de Licencia de Antivirus', max_length=200, verbose_name='Nombre del Ítem')),
                ('descripcion', models.TextField(blank=True, verbose_name='Descripción')),
                ('requiere_proveedor', models.BooleanField(default=False, verbose_name='¿Requiere Proveedor?')),
                ('nombre_responsable_proveedor', models.CharField(blank=True, help_text='Ej: Responsable de Compras, Gerente Comercial', max_length=150, verbose_name='Responsable del Proveedor')),
                ('presupuesto_planificado', models.DecimalField(decimal_places=2, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Presupuesto Planificado')),
                ('presupuesto_ejecutado', models.DecimalField(decimal_places=2, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Presupuesto Ejecutado')),
                ('fecha_inicio', models.DateField(verbose_name='Fecha de Inicio')),
                ('duracion_dias', models.IntegerField(help_text='Días que tomará este ítem', validators=[django.core.validators.MinValueValidator(1)], verbose_name='Duración en Días')),
                ('fecha_fin', models.DateField(help_text='Se calcula: fecha_inicio + duracion_dias', verbose_name='Fecha de Fin (Calculada)')),
                ('tiene_dependencia', models.BooleanField(default=False, help_text='Si depende de otro ítem para iniciar', verbose_name='¿Tiene Dependencia?')),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('en_proceso', 'En Proceso'), ('completado', 'Completado'), ('bloqueado', 'Bloqueado por Dependencia')], default='pendiente', max_length=20, verbose_name='Estado del Ítem')),
                ('porcentaje_avance', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Avance (%)')),
            ],
            options={
                'verbose_name': 'Ítem de Proyecto',
                'verbose_name_plural': 'Ítems de Proyecto',
                'db_table': 'items_proyecto',
                'ordering': ['proyecto', 'numero_item'],
            },
        ),
        migrations.RemoveIndex(
            model_name='proyectocierrebrecha',
            name='proyectos_c_fecha_i_4c4135_idx',
        ),
        migrations.RemoveIndex(
            model_name='proyectocierrebrecha',
            name='proyectos_c_fecha_f_25ba5a_idx',
        ),
        migrations.RemoveField(
            model_name='proyectocierrebrecha',
            name='acciones_mejora_continua',
        ),
        migrations.RemoveField(
            model_name='proyectocierrebrecha',
            name='auditor_verificacion',
        ),
        migrations.RemoveField(
            model_name='proyectocierrebrecha',
            name='canal_comunicacion',
        ),
        migrations.RemoveField(
            model_name='proyectocierrebrecha',
            name='control_no_conforme',
        ),
        migrations.RemoveField(
            model_name='proyectocierrebrecha',
            name='criterios_validacion',
        ),
        migrations.RemoveField(
            model_name='proyectocierrebrecha',
            name='equipo_implementacion',
        ),
        migrations.RemoveField(
            model_name='proyectocierrebrecha',
            name='estrategia_cierre',
        ),
        migrations.RemoveField(
            model_name='proyectocierrebrecha',
            name='evidencia_no_conformidad',
        ),
        migrations.RemoveField(
            model_name='proyectocierrebrecha',
            name='fecha_cierre_formal',
        ),
        migrations.RemoveField(
            model_name='proyectocierrebrecha',
            name='fecha_cierre_tecnico',
        ),
        migrations.RemoveField(
            model_name='proyectocierrebrecha',
            name='fecha_identificacion_gap',
        ),
        migrations.RemoveField(
            model_name='proyectocierrebrecha',
            name='frecuencia_reporte',
        ),
        migrations.RemoveField(
            model_name='proyectocierrebrecha',
            name='impacto_riesgo',
        ),
        migrations.RemoveField(
            model_name='proyectocierrebrecha',
            name='metodo_verificacion',
        ),
        migrations.RemoveField(
            model_name='proyectocierrebrecha',
            name='metricas_desempeno',
        ),
        migrations.RemoveField(
            model_name='proyectocierrebrecha',
            name='nivel_criticidad_original',
        ),
        migrations.RemoveField(
            model_name='proyectocierrebrecha',
            name='normativa',
        ),
        migrations.RemoveField(
            model_name='proyectocierrebrecha',
            name='presupuesto_asignado',
        ),
        migrations.RemoveField(
            model_name='proyectocierrebrecha',
            name='presupuesto_gastado',
        ),
        migrations.RemoveField(
            model_name='proyectocierrebrecha',
            name='recomendaciones_futuros_gap',
        ),
        migrations.RemoveField(
            model_name='proyectocierrebrecha',
            name='recursos_humanos_asignados',
        ),
        migrations.RemoveField(
            model_name='proyectocierrebrecha',
            name='recursos_tecnicos',
        ),
        migrations.RemoveField(
            model_name='proyectocierrebrecha',
            name='responsable_validacion',
        ),
        migrations.RemoveField(
            model_name='proyectocierrebrecha',
            name='restricciones',
        ),
        migrations.RemoveField(
            model_name='proyectocierrebrecha',
            name='supuestos',
        ),
        migrations.RemoveField(
            model_name='proyectocierrebrecha',
            name='tipo_brecha',
        ),
        migrations.RemoveField(
            model_name='proyectocierrebrecha',
            name='umbrales_alerta',
        ),
        migrations.AddField(
            model_name='proyectocierrebrecha',
            name='modo_presupuesto',
            field=models.CharField(choices=[('global', 'Presupuesto Global'), ('por_items', 'Presupuesto por Ítems')], default='global', help_text='Global: monto único. Por ítems: suma de ítems individuales', max_length=20, verbose_name='Modo de Presupuesto'),
        ),
        migrations.AddField(
            model_name='proyectocierrebrecha',
            name='presupuesto_global',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Solo aplica si modo_presupuesto = "global"', max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Presupuesto Global'),
        ),
        migrations.AddField(
            model_name='proyectocierrebrecha',
            name='presupuesto_global_gastado',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Presupuesto Global Gastado'),
        ),
        migrations.AlterField(
            model_name='proyectocierrebrecha',
            name='alcance_proyecto',
            field=models.TextField(help_text='Qué se incluye y qué no', verbose_name='Alcance del Proyecto'),
        ),
        migrations.AlterField(
            model_name='proyectocierrebrecha',
            name='calculo_nivel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='proyectos_remediacion', to='respuestas.calculonivel', verbose_name='Brecha GAP Asociada'),
        ),
        migrations.AlterField(
            model_name='proyectocierrebrecha',
            name='criterios_aceptacion',
            field=models.TextField(help_text='Condiciones para dar por cerrado el proyecto', verbose_name='Criterios de Aceptación'),
        ),
        migrations.AlterField(
            model_name='proyectocierrebrecha',
            name='descripcion',
            field=models.TextField(max_length=1000, verbose_name='Descripción del Proyecto'),
        ),
        migrations.AlterField(
            model_name='proyectocierrebrecha',
            name='dueno_proyecto',
            field=models.ForeignKey(help_text='Responsable general del proyecto', on_delete=django.db.models.deletion.PROTECT, related_name='proyectos_propietario', to=settings.AUTH_USER_MODEL, verbose_name='Dueño del Proyecto'),
        ),
        migrations.AlterField(
            model_name='proyectocierrebrecha',
            name='fecha_fin_estimada',
            field=models.DateField(verbose_name='Fecha de Fin Estimada'),
        ),
        migrations.AlterField(
            model_name='proyectocierrebrecha',
            name='fecha_fin_real',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de Fin Real'),
        ),
        migrations.AlterField(
            model_name='proyectocierrebrecha',
            name='fecha_inicio',
            field=models.DateField(verbose_name='Fecha de Inicio'),
        ),
        migrations.AlterField(
            model_name='proyectocierrebrecha',
            name='lecciones_aprendidas',
            field=models.TextField(blank=True, verbose_name='Lecciones Aprendidas'),
        ),
        migrations.AlterField(
            model_name='proyectocierrebrecha',
            name='moneda',
            field=models.CharField(choices=[('USD', 'USD - Dólar Estadounidense'), ('EUR', 'EUR - Euro'), ('PEN', 'PEN - Sol Peruano'), ('COP', 'COP - Peso Colombiano'), ('MXN', 'MXN - Peso Mexicano')], default='USD', max_length=3, verbose_name='Moneda'),
        ),
        migrations.AlterField(
            model_name='proyectocierrebrecha',
            name='nombre_proyecto',
            field=models.CharField(max_length=200, verbose_name='Nombre del Proyecto'),
        ),
        migrations.AlterField(
            model_name='proyectocierrebrecha',
            name='objetivos_especificos',
            field=models.TextField(help_text='Lista de objetivos medibles', verbose_name='Objetivos Específicos'),
        ),
        migrations.AlterField(
            model_name='proyectocierrebrecha',
            name='preguntas_abordadas',
            field=models.ManyToManyField(blank=True, related_name='proyectos_remediacion', to='encuestas.pregunta', verbose_name='Preguntas Abordadas'),
        ),
        migrations.AlterField(
            model_name='proyectocierrebrecha',
            name='prioridad',
            field=models.CharField(choices=[('critica', 'Crítica'), ('alta', 'Alta'), ('media', 'Media'), ('baja', 'Baja')], help_text='Derivada de la criticidad del GAP', max_length=20, verbose_name='Prioridad'),
        ),
        migrations.AlterField(
            model_name='proyectocierrebrecha',
            name='responsable_implementacion',
            field=models.ForeignKey(help_text='Quien ejecuta las tareas', on_delete=django.db.models.deletion.PROTECT, related_name='proyectos_responsable', to=settings.AUTH_USER_MODEL, verbose_name='Responsable de Implementación'),
        ),
        migrations.AlterField(
            model_name='proyectocierrebrecha',
            name='riesgos_proyecto',
            field=models.TextField(blank=True, help_text='Riesgos que podrían afectar el proyecto', verbose_name='Riesgos Identificados'),
        ),
        migrations.AlterField(
            model_name='proyectocierrebrecha',
            name='validador_interno',
            field=models.ForeignKey(blank=True, help_text='Quien aprueba el proyecto', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='proyectos_validador', to=settings.AUTH_USER_MODEL, verbose_name='Validador Interno'),
        ),
        migrations.AlterField(
            model_name='proyectocierrebrecha',
            name='version',
            field=models.IntegerField(default=1, verbose_name='Versión del Proyecto'),
        ),
        migrations.AddField(
            model_name='itemproyecto',
            name='item_dependencia',
            field=models.ForeignKey(blank=True, help_text='Solo si tiene_dependencia=True', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='items_dependientes', to='proyectos_remediacion.itemproyecto', verbose_name='Ítem del que Depende'),
        ),
        migrations.AddField(
            model_name='itemproyecto',
            name='proveedor',
            field=models.ForeignKey(blank=True, help_text='Solo si requiere_proveedor=True', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='items_proyecto', to='proveedores.proveedor', verbose_name='Proveedor'),
        ),
        migrations.AddField(
            model_name='itemproyecto',
            name='proyecto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='proyectos_remediacion.proyectocierrebrecha', verbose_name='Proyecto'),
        ),
        migrations.AddField(
            model_name='itemproyecto',
            name='responsable_ejecucion',
            field=models.ForeignKey(help_text='Quien ejecuta este ítem (Obligatorio)', on_delete=django.db.models.deletion.PROTECT, related_name='items_responsable', to=settings.AUTH_USER_MODEL, verbose_name='Responsable de Ejecución'),
        ),
        migrations.AddIndex(
            model_name='itemproyecto',
            index=models.Index(fields=['proyecto', 'estado'], name='items_proye_proyect_0865f3_idx'),
        ),
        migrations.AddIndex(
            model_name='itemproyecto',
            index=models.Index(fields=['responsable_ejecucion'], name='items_proye_respons_da7fa3_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='itemproyecto',
            unique_together={('proyecto', 'numero_item')},
        ),
    ]
