# Generated by Django 5.0 on 2026-01-27 03:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proveedores', '0002_proveedor_empresa_alter_proveedor_ruc_and_more'),
        ('proyectos_remediacion', '0002_itemproyecto_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AprobacionGAP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, verbose_name='Fecha de Actualización')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('fecha_solicitud', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de solicitud')),
                ('comentarios_solicitud', models.TextField(blank=True, help_text='Comentarios del responsable al solicitar la aprobación', verbose_name='Comentarios de la solicitud')),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('aprobado', 'Aprobado'), ('rechazado', 'Rechazado')], default='pendiente', max_length=20, verbose_name='Estado')),
                ('fecha_revision', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de revisión')),
                ('observaciones', models.TextField(blank=True, help_text='Observaciones del validador (requerido si rechaza)', verbose_name='Observaciones')),
                ('documentos_adjuntos', models.JSONField(blank=True, default=list, help_text='Lista de URLs de documentos de evidencia', verbose_name='Documentos adjuntos')),
                ('items_completados', models.IntegerField(default=0, verbose_name='Ítems completados')),
                ('items_totales', models.IntegerField(default=0, verbose_name='Ítems totales')),
                ('presupuesto_ejecutado', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Presupuesto ejecutado')),
                ('presupuesto_planificado', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Presupuesto planificado')),
                ('gap_original', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='GAP original')),
            ],
            options={
                'verbose_name': 'Aprobación de GAP',
                'verbose_name_plural': 'Aprobaciones de GAP',
                'ordering': ['-fecha_solicitud'],
            },
        ),
        migrations.RemoveIndex(
            model_name='itemproyecto',
            name='items_proye_proyect_0865f3_idx',
        ),
        migrations.RemoveIndex(
            model_name='itemproyecto',
            name='items_proye_respons_da7fa3_idx',
        ),
        migrations.AlterUniqueTogether(
            name='itemproyecto',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='itemproyecto',
            constraint=models.UniqueConstraint(fields=('proyecto', 'numero_item'), name='unique_numero_item_por_proyecto'),
        ),
        migrations.AlterModelTable(
            name='itemproyecto',
            table=None,
        ),
        migrations.AddField(
            model_name='aprobaciongap',
            name='proyecto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aprobaciones', to='proyectos_remediacion.proyectocierrebrecha', verbose_name='Proyecto'),
        ),
        migrations.AddField(
            model_name='aprobaciongap',
            name='solicitado_por',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='aprobaciones_solicitadas', to=settings.AUTH_USER_MODEL, verbose_name='Solicitado por'),
        ),
        migrations.AddField(
            model_name='aprobaciongap',
            name='validador',
            field=models.ForeignKey(help_text='Usuario que debe aprobar o rechazar', on_delete=django.db.models.deletion.PROTECT, related_name='aprobaciones_asignadas', to=settings.AUTH_USER_MODEL, verbose_name='Validador'),
        ),
        migrations.AddIndex(
            model_name='aprobaciongap',
            index=models.Index(fields=['estado', 'fecha_solicitud'], name='proyectos_r_estado_499703_idx'),
        ),
        migrations.AddIndex(
            model_name='aprobaciongap',
            index=models.Index(fields=['validador', 'estado'], name='proyectos_r_validad_b9789b_idx'),
        ),
    ]
