# Generated by Django 5.0 on 2026-01-27 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyectos_remediacion', '0003_aprobaciongap_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemproyecto',
            name='fecha_completado',
            field=models.DateField(blank=True, help_text='Fecha en que el ítem fue marcado como completado', null=True, verbose_name='Fecha de Completado'),
        ),
        migrations.AddField(
            model_name='itemproyecto',
            name='observaciones',
            field=models.TextField(blank=True, verbose_name='Observaciones'),
        ),
    ]
