# Generated by Django 5.2.12 on 2026-03-10 02:17

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('asignaciones', '0006_alter_asignacion_estado'),
        ('asignaciones_iq', '0003_respuestaevaluacioniq'),
        ('documentos', '0001_initial'),
        ('empresas', '0002_empresa_pais_empresa_pais_otro_empresa_sector_and_more'),
        ('encuestas', '0002_evaluacionempresa_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Respuesta',
            fields=[
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, verbose_name='Fecha de Actualización')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('respuesta', models.CharField(blank=True, choices=[('NO_APLICA', 'No Aplica'), ('SI_CUMPLE', 'Sí Cumple'), ('CUMPLE_PARCIAL', 'Cumple Parcialmente'), ('NO_CUMPLE', 'No Cumple')], default=None, help_text='El usuario solo puede marcar NO_APLICA. Si deja vacío, sube evidencias para que el auditor califique.', max_length=20, null=True, verbose_name='Respuesta del Usuario')),
                ('justificacion', models.TextField(blank=True, default='', help_text='Obligatorio siempre (mínimo 10 caracteres). Para NO_APLICA: explica por qué no aplica.', verbose_name='Justificación del Usuario')),
                ('comentarios_adicionales', models.TextField(blank=True, default='', verbose_name='Comentarios Adicionales del Usuario')),
                ('calificacion_auditor', models.CharField(blank=True, choices=[('SI_CUMPLE', 'Sí Cumple'), ('CUMPLE_PARCIAL', 'Cumple Parcialmente'), ('NO_CUMPLE', 'No Cumple')], help_text='SI_CUMPLE / CUMPLE_PARCIAL / NO_CUMPLE — asignado por el Auditor', max_length=20, null=True, verbose_name='Calificación del Auditor')),
                ('comentarios_auditor', models.TextField(blank=True, default='', help_text='Observaciones del auditor sobre la respuesta', verbose_name='Comentarios del Auditor')),
                ('recomendaciones_auditor', models.TextField(blank=True, default='', help_text='Qué debe mejorar la empresa para subir de nivel', verbose_name='Recomendaciones del Auditor')),
                ('fecha_auditoria', models.DateTimeField(blank=True, help_text='Fecha en que el auditor calificó esta respuesta', null=True, verbose_name='Fecha de Auditoría')),
                ('nivel_madurez', models.DecimalField(decimal_places=1, default=0.0, help_text='Asignado por el auditor (0–5 en incrementos de 0.5)', max_digits=2, verbose_name='Nivel de Madurez')),
                ('estado', models.CharField(choices=[('borrador', 'Borrador'), ('enviado', 'Enviado'), ('pendiente_auditoria', 'Pendiente de Auditoría'), ('auditado', 'Auditado'), ('modificado_admin', 'Modificado por Admin')], default='borrador', max_length=25, verbose_name='Estado')),
                ('respondido_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Respuesta')),
                ('modificado_at', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de última modificación')),
                ('version', models.IntegerField(default=1, verbose_name='Versión')),
                ('asignacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='respuestas', to='asignaciones.asignacion', verbose_name='Asignación')),
                ('auditado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='respuestas_auditadas', to=settings.AUTH_USER_MODEL, verbose_name='Auditado Por')),
                ('modificado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='respuestas_modificadas', to=settings.AUTH_USER_MODEL, verbose_name='Última modificación por')),
                ('pregunta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='respuestas', to='encuestas.pregunta', verbose_name='Pregunta')),
                ('respondido_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='respuestas_creadas', to=settings.AUTH_USER_MODEL, verbose_name='Respondido por')),
            ],
            options={
                'verbose_name': 'Respuesta',
                'verbose_name_plural': 'Respuestas',
                'db_table': 'respuestas',
                'ordering': ['-respondido_at'],
            },
        ),
        migrations.CreateModel(
            name='HistorialRespuesta',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tipo_cambio', models.CharField(choices=[('creacion', 'Creación Inicial'), ('modificacion_respuesta', 'Modificación de Respuesta'), ('modificacion_justificacion', 'Modificación de Justificación'), ('agregado_evidencia', 'Agregado de Evidencia'), ('eliminado_evidencia', 'Eliminación de Evidencia'), ('modificacion_comentarios', 'Modificación de Comentarios')], max_length=50, verbose_name='Tipo de Cambio')),
                ('valor_anterior_respuesta', models.CharField(blank=True, max_length=20, null=True, verbose_name='Respuesta Anterior')),
                ('valor_anterior_justificacion', models.TextField(blank=True, null=True, verbose_name='Justificación Anterior')),
                ('valor_anterior_comentarios', models.TextField(blank=True, null=True, verbose_name='Comentarios Anteriores')),
                ('valor_nuevo_respuesta', models.CharField(blank=True, max_length=20, null=True, verbose_name='Respuesta Nueva')),
                ('valor_nuevo_justificacion', models.TextField(blank=True, null=True, verbose_name='Justificación Nueva')),
                ('valor_nuevo_comentarios', models.TextField(blank=True, null=True, verbose_name='Comentarios Nuevos')),
                ('motivo', models.TextField(blank=True, verbose_name='Motivo del Cambio')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='Dirección IP')),
                ('user_agent', models.CharField(blank=True, max_length=255, verbose_name='User Agent')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Fecha y Hora del Cambio')),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Usuario que realizó el cambio')),
                ('respuesta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historial', to='respuestas.respuesta', verbose_name='Respuesta')),
            ],
            options={
                'verbose_name': 'Historial de Respuesta',
                'verbose_name_plural': 'Historial de Respuestas',
                'db_table': 'historial_respuestas',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='Evidencia',
            fields=[
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, verbose_name='Fecha de Actualización')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('codigo_documento', models.CharField(db_index=True, default='SIN-CODIGO', help_text='Código único del documento (ej: POL-SEG-001, PROC-TI-045)', max_length=50, verbose_name='Código de Documento')),
                ('tipo_documento_enum', models.CharField(choices=[('politica', 'Política'), ('norma', 'Norma'), ('procedimiento', 'Procedimiento'), ('formato_interno', 'Formato Interno'), ('otro', 'Otro')], default='otro', max_length=50, verbose_name='Tipo de Documento')),
                ('titulo_documento', models.CharField(default='Documento sin título', max_length=60, verbose_name='Título del Documento')),
                ('objetivo_documento', models.CharField(default='Sin objetivo especificado', max_length=180, verbose_name='Objetivo del Documento')),
                ('fecha_ultima_actualizacion', models.DateField(auto_now_add=True, verbose_name='Fecha de Última Actualización')),
                ('nombre_archivo_original', models.CharField(blank=True, default='', max_length=255, verbose_name='Nombre Archivo Original')),
                ('archivo', models.CharField(help_text='Ruta del archivo en Supabase Storage (ej: evidencias/empresa_123/archivo.pdf)', max_length=500, verbose_name='Ruta del Archivo en Supabase')),
                ('tamanio_bytes', models.BigIntegerField(default=0, verbose_name='Tamaño en Bytes')),
                ('documento_oficial', models.ForeignKey(blank=True, help_text='Si selecciona un documento del Módulo de Gestión Documental, se vinculará aquí.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='evidencias_utilizadas', to='documentos.documento', verbose_name='Documento del Maestro')),
                ('respuesta_iq', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='evidencias', to='asignaciones_iq.respuestaevaluacioniq', verbose_name='Respuesta IQ')),
                ('subido_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='evidencias_subidas', to=settings.AUTH_USER_MODEL, verbose_name='Subido por')),
                ('respuesta', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='evidencias', to='respuestas.respuesta', verbose_name='Respuesta')),
            ],
            options={
                'verbose_name': 'Evidencia',
                'verbose_name_plural': 'Evidencias',
                'db_table': 'evidencias',
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='CalculoNivel',
            fields=[
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, verbose_name='Fecha de Actualización')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nivel_deseado', models.DecimalField(decimal_places=1, help_text='Nivel objetivo definido por el administrador (1-5)', max_digits=2, verbose_name='Nivel Deseado')),
                ('nivel_actual', models.DecimalField(decimal_places=1, help_text='Promedio de nivel_madurez de todas las respuestas del usuario', max_digits=2, verbose_name='Nivel Actual')),
                ('gap', models.DecimalField(decimal_places=1, help_text='Diferencia: Nivel Deseado - Nivel Actual', max_digits=3, verbose_name='GAP')),
                ('clasificacion_gap', models.CharField(choices=[('critico', 'Crítico'), ('alto', 'Alto'), ('medio', 'Medio'), ('bajo', 'Bajo'), ('cumplido', 'Cumplido'), ('superado', 'Superado')], max_length=20, verbose_name='Clasificación del GAP')),
                ('total_preguntas', models.IntegerField(default=0, verbose_name='Total de Preguntas')),
                ('respuestas_si_cumple', models.IntegerField(default=0, verbose_name='Respuestas Sí Cumple')),
                ('respuestas_cumple_parcial', models.IntegerField(default=0, verbose_name='Respuestas Cumple Parcial')),
                ('respuestas_no_cumple', models.IntegerField(default=0, verbose_name='Respuestas No Cumple')),
                ('respuestas_no_aplica', models.IntegerField(default=0, verbose_name='Respuestas No Aplica')),
                ('porcentaje_cumplimiento', models.DecimalField(decimal_places=2, default=0, help_text='Porcentaje de preguntas con Sí Cumple o Cumple Parcial', max_digits=5, verbose_name='% Cumplimiento')),
                ('calculado_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de Cálculo')),
                ('asignacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calculos_nivel', to='asignaciones.asignacion', verbose_name='Asignación')),
                ('dimension', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calculos', to='encuestas.dimension', verbose_name='Dimensión')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calculos_nivel', to='empresas.empresa', verbose_name='Empresa')),
                ('evaluacion_empresa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='calculos_nivel', to='encuestas.evaluacionempresa', verbose_name='Evaluación Empresa')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calculos_nivel', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Cálculo de Nivel',
                'verbose_name_plural': 'Cálculos de Nivel',
                'db_table': 'calculos_nivel',
                'ordering': ['-calculado_at'],
                'indexes': [models.Index(fields=['empresa', 'dimension'], name='calculos_ni_empresa_807583_idx'), models.Index(fields=['usuario', 'dimension'], name='calculos_ni_usuario_4e7520_idx'), models.Index(fields=['clasificacion_gap'], name='calculos_ni_clasifi_bc9824_idx'), models.Index(fields=['calculado_at'], name='calculos_ni_calcula_f89668_idx')],
                'unique_together': {('asignacion', 'dimension')},
            },
        ),
        migrations.AddIndex(
            model_name='respuesta',
            index=models.Index(fields=['asignacion', 'estado'], name='respuestas_asignac_169af9_idx'),
        ),
        migrations.AddIndex(
            model_name='respuesta',
            index=models.Index(fields=['pregunta'], name='respuestas_pregunt_c471e6_idx'),
        ),
        migrations.AddIndex(
            model_name='respuesta',
            index=models.Index(fields=['respondido_por'], name='respuestas_respond_e0a93c_idx'),
        ),
        migrations.AddIndex(
            model_name='respuesta',
            index=models.Index(fields=['auditado_por'], name='respuestas_auditad_df6fa1_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='respuesta',
            unique_together={('asignacion', 'pregunta')},
        ),
        migrations.AddIndex(
            model_name='historialrespuesta',
            index=models.Index(fields=['respuesta', '-timestamp'], name='historial_r_respues_5d11b2_idx'),
        ),
        migrations.AddIndex(
            model_name='historialrespuesta',
            index=models.Index(fields=['usuario', '-timestamp'], name='historial_r_usuario_87a15a_idx'),
        ),
        migrations.AddIndex(
            model_name='historialrespuesta',
            index=models.Index(fields=['tipo_cambio'], name='historial_r_tipo_ca_b2e6fb_idx'),
        ),
        migrations.AddIndex(
            model_name='evidencia',
            index=models.Index(fields=['respuesta'], name='evidencias_respues_bcc009_idx'),
        ),
        migrations.AddIndex(
            model_name='evidencia',
            index=models.Index(fields=['tipo_documento_enum'], name='evidencias_tipo_do_ec37cd_idx'),
        ),
        migrations.AddIndex(
            model_name='evidencia',
            index=models.Index(fields=['subido_por'], name='evidencias_subido__87b923_idx'),
        ),
        migrations.AddIndex(
            model_name='evidencia',
            index=models.Index(fields=['codigo_documento'], name='evidencias_codigo__1fc639_idx'),
        ),
    ]
