# Generated by Django 5.0 on 2025-12-19 03:59

import apps.respuestas.models
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('asignaciones', '0003_asignacion_comentarios_revision_and_more'),
        ('empresas', '0002_empresa_pais_empresa_pais_otro_empresa_sector_and_more'),
        ('encuestas', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CalculoNivel',
            fields=[
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, verbose_name='Fecha de Actualización')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nivel_actual', models.IntegerField(choices=[(1, 'Nivel 1'), (2, 'Nivel 2'), (3, 'Nivel 3'), (4, 'Nivel 4'), (5, 'Nivel 5')], verbose_name='Nivel Actual')),
                ('nivel_deseado', models.IntegerField(choices=[(1, 'Nivel 1'), (2, 'Nivel 2'), (3, 'Nivel 3'), (4, 'Nivel 4'), (5, 'Nivel 5')], verbose_name='Nivel Deseado')),
                ('gap', models.IntegerField(verbose_name='GAP')),
                ('total_preguntas', models.IntegerField(default=0)),
                ('respuestas_yes', models.IntegerField(default=0)),
                ('respuestas_no', models.IntegerField(default=0)),
                ('respuestas_na', models.IntegerField(default=0)),
                ('porcentaje_cumplimiento', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('clasificacion_gap', models.CharField(choices=[('cumplido', 'Cumplido'), ('superado', 'Superado'), ('bajo', 'Bajo'), ('medio', 'Medio'), ('alto', 'Alto'), ('critico', 'Crítico')], max_length=20)),
                ('calculado_at', models.DateTimeField(auto_now=True)),
                ('asignacion', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='calculo_nivel', to='asignaciones.asignacion', verbose_name='Asignación')),
                ('dimension', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calculos', to='encuestas.dimension', verbose_name='Dimensión')),
            ],
            options={
                'verbose_name': 'Cálculo de Nivel',
                'verbose_name_plural': 'Cálculos de Nivel',
                'db_table': 'calculos_nivel',
                'ordering': ['-calculado_at'],
            },
        ),
        migrations.CreateModel(
            name='Iniciativa',
            fields=[
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, verbose_name='Fecha de Actualización')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=200)),
                ('descripcion', models.TextField()),
                ('objetivo', models.TextField()),
                ('estado', models.CharField(choices=[('planificada', 'Planificada'), ('en_progreso', 'En Progreso'), ('completada', 'Completada'), ('cancelada', 'Cancelada'), ('retrasada', 'Retrasada')], default='planificada', max_length=20)),
                ('prioridad', models.CharField(choices=[('critica', 'Crítica'), ('alta', 'Alta'), ('media', 'Media'), ('baja', 'Baja')], default='media', max_length=20)),
                ('fecha_inicio_estimada', models.DateField()),
                ('fecha_termino_estimada', models.DateField()),
                ('fecha_inicio_real', models.DateField(blank=True, null=True)),
                ('fecha_termino_real', models.DateField(blank=True, null=True)),
                ('presupuesto_estimado', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('costo_real', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('moneda', models.CharField(default='USD', max_length=3)),
                ('dias_alerta_previo', models.IntegerField(default=7)),
                ('alerta_enviada', models.BooleanField(default=False)),
                ('fecha_alerta_enviada', models.DateTimeField(blank=True, null=True)),
                ('porcentaje_avance', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('asignado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='iniciativas_creadas', to=settings.AUTH_USER_MODEL)),
                ('calculo_nivel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='iniciativas', to='respuestas.calculonivel')),
                ('dimension', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='iniciativas', to='encuestas.dimension')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='iniciativas', to='empresas.empresa')),
                ('responsable', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='iniciativas_asignadas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Iniciativa',
                'verbose_name_plural': 'Iniciativas',
                'db_table': 'iniciativas',
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='Respuesta',
            fields=[
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, verbose_name='Fecha de Actualización')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('respuesta', models.CharField(choices=[('YES', 'Sí'), ('NO', 'No'), ('NOT_APPLICABLE', 'No Aplica')], max_length=20, verbose_name='Respuesta')),
                ('justificacion', models.TextField(verbose_name='Justificación')),
                ('comentarios_adicionales', models.TextField(blank=True, default='', verbose_name='Comentarios Adicionales')),
                ('estado', models.CharField(choices=[('borrador', 'Borrador'), ('enviado', 'Enviado'), ('modificado_admin', 'Modificado por Admin')], default='borrador', max_length=20, verbose_name='Estado')),
                ('respondido_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Respuesta')),
                ('modificado_at', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de última modificación')),
                ('version', models.IntegerField(default=1, verbose_name='Versión')),
                ('asignacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='respuestas', to='asignaciones.asignacion', verbose_name='Asignación')),
                ('modificado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='respuestas_modificadas', to=settings.AUTH_USER_MODEL, verbose_name='Última modificación por')),
                ('pregunta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='respuestas', to='encuestas.pregunta', verbose_name='Pregunta')),
                ('respondido_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='respuestas_creadas', to=settings.AUTH_USER_MODEL, verbose_name='Respondido por')),
            ],
            options={
                'verbose_name': 'Respuesta',
                'verbose_name_plural': 'Respuestas',
                'db_table': 'respuestas',
                'ordering': ['-respondido_at'],
            },
        ),
        migrations.CreateModel(
            name='HistorialRespuesta',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tipo_cambio', models.CharField(choices=[('creacion', 'Creación Inicial'), ('modificacion_respuesta', 'Modificación de Respuesta'), ('modificacion_justificacion', 'Modificación de Justificación'), ('agregado_evidencia', 'Agregado de Evidencia'), ('eliminado_evidencia', 'Eliminación de Evidencia'), ('modificacion_comentarios', 'Modificación de Comentarios')], max_length=50, verbose_name='Tipo de Cambio')),
                ('valor_anterior_respuesta', models.CharField(blank=True, max_length=20, null=True, verbose_name='Respuesta Anterior')),
                ('valor_anterior_justificacion', models.TextField(blank=True, null=True, verbose_name='Justificación Anterior')),
                ('valor_anterior_comentarios', models.TextField(blank=True, null=True, verbose_name='Comentarios Anteriores')),
                ('valor_nuevo_respuesta', models.CharField(blank=True, max_length=20, null=True, verbose_name='Respuesta Nueva')),
                ('valor_nuevo_justificacion', models.TextField(blank=True, null=True, verbose_name='Justificación Nueva')),
                ('valor_nuevo_comentarios', models.TextField(blank=True, null=True, verbose_name='Comentarios Nuevos')),
                ('motivo', models.TextField(blank=True, verbose_name='Motivo del Cambio')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='Dirección IP')),
                ('user_agent', models.CharField(blank=True, max_length=255, verbose_name='User Agent')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Fecha y Hora del Cambio')),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Usuario que realizó el cambio')),
                ('respuesta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historial', to='respuestas.respuesta', verbose_name='Respuesta')),
            ],
            options={
                'verbose_name': 'Historial de Respuesta',
                'verbose_name_plural': 'Historial de Respuestas',
                'db_table': 'historial_respuestas',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='Evidencia',
            fields=[
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, verbose_name='Fecha de Actualización')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('codigo_documento', models.CharField(db_index=True, default='SIN-CODIGO', help_text='Código único del documento (ej: POL-SEG-001, PROC-TI-045)', max_length=50, verbose_name='Código de Documento')),
                ('tipo_documento_enum', models.CharField(choices=[('politica', 'Política'), ('norma', 'Norma'), ('procedimiento', 'Procedimiento'), ('formato_interno', 'Formato Interno'), ('otro', 'Otro')], default='otro', max_length=50, verbose_name='Tipo de Documento')),
                ('titulo_documento', models.CharField(default='Documento sin título', max_length=60, verbose_name='Título del Documento')),
                ('objetivo_documento', models.CharField(default='Sin objetivo especificado', max_length=180, verbose_name='Objetivo del Documento')),
                ('fecha_ultima_actualizacion', models.DateField(auto_now_add=True, verbose_name='Fecha de Última Actualización')),
                ('nombre_archivo_original', models.CharField(blank=True, default='', max_length=255, verbose_name='Nombre Archivo Original')),
                ('archivo', models.FileField(upload_to=apps.respuestas.models.evidencia_upload_path, verbose_name='Archivo')),
                ('tamanio_bytes', models.BigIntegerField(default=0, verbose_name='Tamaño en Bytes')),
                ('subido_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='evidencias_subidas', to=settings.AUTH_USER_MODEL, verbose_name='Subido por')),
                ('respuesta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evidencias', to='respuestas.respuesta', verbose_name='Respuesta')),
            ],
            options={
                'verbose_name': 'Evidencia',
                'verbose_name_plural': 'Evidencias',
                'db_table': 'evidencias',
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='TipoDocumento',
            fields=[
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, verbose_name='Fecha de Actualización')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre del Tipo')),
                ('descripcion', models.TextField(blank=True, verbose_name='Descripción')),
                ('requiere_fecha', models.BooleanField(default=True, verbose_name='Requiere Fecha de Creación')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tipos_documento', to='empresas.empresa', verbose_name='Empresa')),
            ],
            options={
                'verbose_name': 'Tipo de Documento',
                'verbose_name_plural': 'Tipos de Documento',
                'db_table': 'tipos_documento',
                'ordering': ['empresa', 'nombre'],
            },
        ),
        migrations.AddIndex(
            model_name='calculonivel',
            index=models.Index(fields=['asignacion'], name='calculos_ni_asignac_781ef9_idx'),
        ),
        migrations.AddIndex(
            model_name='calculonivel',
            index=models.Index(fields=['dimension'], name='calculos_ni_dimensi_460388_idx'),
        ),
        migrations.AddIndex(
            model_name='iniciativa',
            index=models.Index(fields=['calculo_nivel'], name='iniciativas_calculo_a84db2_idx'),
        ),
        migrations.AddIndex(
            model_name='iniciativa',
            index=models.Index(fields=['responsable', 'estado'], name='iniciativas_respons_8254a7_idx'),
        ),
        migrations.AddIndex(
            model_name='iniciativa',
            index=models.Index(fields=['fecha_termino_estimada'], name='iniciativas_fecha_t_fcf421_idx'),
        ),
        migrations.AddIndex(
            model_name='respuesta',
            index=models.Index(fields=['asignacion', 'estado'], name='respuestas_asignac_169af9_idx'),
        ),
        migrations.AddIndex(
            model_name='respuesta',
            index=models.Index(fields=['pregunta'], name='respuestas_pregunt_c471e6_idx'),
        ),
        migrations.AddIndex(
            model_name='respuesta',
            index=models.Index(fields=['respondido_por'], name='respuestas_respond_e0a93c_idx'),
        ),
        migrations.AddIndex(
            model_name='respuesta',
            index=models.Index(fields=['modificado_por'], name='respuestas_modific_9f3898_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='respuesta',
            unique_together={('asignacion', 'pregunta')},
        ),
        migrations.AddIndex(
            model_name='historialrespuesta',
            index=models.Index(fields=['respuesta', '-timestamp'], name='historial_r_respues_5d11b2_idx'),
        ),
        migrations.AddIndex(
            model_name='historialrespuesta',
            index=models.Index(fields=['usuario', '-timestamp'], name='historial_r_usuario_87a15a_idx'),
        ),
        migrations.AddIndex(
            model_name='historialrespuesta',
            index=models.Index(fields=['tipo_cambio'], name='historial_r_tipo_ca_b2e6fb_idx'),
        ),
        migrations.AddIndex(
            model_name='evidencia',
            index=models.Index(fields=['respuesta'], name='evidencias_respues_bcc009_idx'),
        ),
        migrations.AddIndex(
            model_name='evidencia',
            index=models.Index(fields=['tipo_documento_enum'], name='evidencias_tipo_do_ec37cd_idx'),
        ),
        migrations.AddIndex(
            model_name='evidencia',
            index=models.Index(fields=['subido_por'], name='evidencias_subido__87b923_idx'),
        ),
        migrations.AddIndex(
            model_name='evidencia',
            index=models.Index(fields=['codigo_documento'], name='evidencias_codigo__1fc639_idx'),
        ),
        migrations.AddIndex(
            model_name='tipodocumento',
            index=models.Index(fields=['empresa', 'activo'], name='tipos_docum_empresa_4aa8f7_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='tipodocumento',
            unique_together={('empresa', 'nombre')},
        ),
    ]
