# Generated by Django 5.0 on 2025-12-19 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('respuestas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='respuesta',
            name='justificacion',
            field=models.TextField(blank=True, default='', help_text='Obligatorio para "Sí Cumple" (mínimo 10 caracteres)', verbose_name='Justificación'),
        ),
        migrations.AlterField(
            model_name='respuesta',
            name='respuesta',
            field=models.CharField(choices=[('SI_CUMPLE', 'Sí Cumple'), ('CUMPLE_PARCIAL', 'Cumple Parcialmente'), ('NO_CUMPLE', 'No Cumple'), ('NO_APLICA', 'No Aplica')], help_text='Nivel de cumplimiento: Sí (1.0), Parcial (0.5), No (0.0), N/A (excluido)', max_length=20, verbose_name='Respuesta'),
        ),
    ]
