# Generated by Django 5.0 on 2025-12-24 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('respuestas', '0002_alter_respuesta_justificacion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='respuesta',
            name='justificacion_madurez',
            field=models.TextField(blank=True, default='', help_text='Explicación de por qué se considera ese nivel de madurez', verbose_name='Justificación del Nivel de Madurez'),
        ),
        migrations.AddField(
            model_name='respuesta',
            name='nivel_madurez',
            field=models.DecimalField(decimal_places=1, default=0.0, help_text='Nivel de madurez de implementación (0 a 5 en incrementos de 0.5). Representa qué tan maduro está el proceso implementado.', max_digits=2, verbose_name='Nivel de Madurez'),
        ),
    ]
