# Generated by Django 5.2.12 on 2026-04-22 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('respuestas', '0003_fix_evidencia_constraint_attnames'),
    ]

    operations = [
        migrations.AddField(
            model_name='calculonivel',
            name='fecha_remediacion',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Remediación'),
        ),
        migrations.AddField(
            model_name='calculonivel',
            name='remediado',
            field=models.BooleanField(default=False, help_text='True cuando el proyecto de cierre de brecha fue aprobado', verbose_name='Remediado'),
        ),
    ]
