# Generated by Django 5.0 on 2025-12-28 00:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asignaciones', '0003_asignacion_comentarios_revision_and_more'),
        ('empresas', '0002_empresa_pais_empresa_pais_otro_empresa_sector_and_more'),
        ('encuestas', '0001_initial'),
        ('respuestas', '0003_respuesta_justificacion_madurez_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='calculonivel',
            name='calculos_ni_asignac_781ef9_idx',
        ),
        migrations.RemoveIndex(
            model_name='calculonivel',
            name='calculos_ni_dimensi_460388_idx',
        ),
        migrations.AlterUniqueTogether(
            name='calculonivel',
            unique_together={('asignacion', 'dimension')},
        ),
        migrations.AddField(
            model_name='calculonivel',
            name='empresa',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='calculos_nivel', to='empresas.empresa', verbose_name='Empresa'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='calculonivel',
            name='respuestas_cumple_parcial',
            field=models.IntegerField(default=0, verbose_name='Respuestas Cumple Parcial'),
        ),
        migrations.AddField(
            model_name='calculonivel',
            name='respuestas_no_aplica',
            field=models.IntegerField(default=0, verbose_name='Respuestas No Aplica'),
        ),
        migrations.AddField(
            model_name='calculonivel',
            name='respuestas_no_cumple',
            field=models.IntegerField(default=0, verbose_name='Respuestas No Cumple'),
        ),
        migrations.AddField(
            model_name='calculonivel',
            name='respuestas_si_cumple',
            field=models.IntegerField(default=0, verbose_name='Respuestas Sí Cumple'),
        ),
        migrations.AddField(
            model_name='calculonivel',
            name='usuario',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, related_name='calculos_nivel', to=settings.AUTH_USER_MODEL, verbose_name='Usuario'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='calculonivel',
            name='calculado_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Fecha de Cálculo'),
        ),
        migrations.AlterField(
            model_name='calculonivel',
            name='clasificacion_gap',
            field=models.CharField(choices=[('critico', 'Crítico'), ('alto', 'Alto'), ('medio', 'Medio'), ('bajo', 'Bajo'), ('cumplido', 'Cumplido'), ('superado', 'Superado')], max_length=20, verbose_name='Clasificación del GAP'),
        ),
        migrations.AlterField(
            model_name='calculonivel',
            name='gap',
            field=models.DecimalField(decimal_places=1, help_text='Diferencia: Nivel Deseado - Nivel Actual', max_digits=3, verbose_name='GAP'),
        ),
        migrations.AlterField(
            model_name='calculonivel',
            name='nivel_actual',
            field=models.DecimalField(decimal_places=1, help_text='Promedio de nivel_madurez de todas las respuestas del usuario', max_digits=2, verbose_name='Nivel Actual'),
        ),
        migrations.AlterField(
            model_name='calculonivel',
            name='nivel_deseado',
            field=models.DecimalField(decimal_places=1, help_text='Nivel objetivo definido por el administrador (1-5)', max_digits=2, verbose_name='Nivel Deseado'),
        ),
        migrations.AlterField(
            model_name='calculonivel',
            name='porcentaje_cumplimiento',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Porcentaje de preguntas con Sí Cumple o Cumple Parcial', max_digits=5, verbose_name='% Cumplimiento'),
        ),
        migrations.AlterField(
            model_name='calculonivel',
            name='total_preguntas',
            field=models.IntegerField(default=0, verbose_name='Total de Preguntas'),
        ),
        migrations.AddIndex(
            model_name='calculonivel',
            index=models.Index(fields=['empresa', 'dimension'], name='calculos_ni_empresa_807583_idx'),
        ),
        migrations.AddIndex(
            model_name='calculonivel',
            index=models.Index(fields=['usuario', 'dimension'], name='calculos_ni_usuario_4e7520_idx'),
        ),
        migrations.AddIndex(
            model_name='calculonivel',
            index=models.Index(fields=['clasificacion_gap'], name='calculos_ni_clasifi_bc9824_idx'),
        ),
        migrations.AddIndex(
            model_name='calculonivel',
            index=models.Index(fields=['calculado_at'], name='calculos_ni_calcula_f89668_idx'),
        ),
        migrations.RemoveField(
            model_name='calculonivel',
            name='respuestas_na',
        ),
        migrations.RemoveField(
            model_name='calculonivel',
            name='respuestas_no',
        ),
        migrations.RemoveField(
            model_name='calculonivel',
            name='respuestas_yes',
        ),
    ]
