# Generated by Django 5.0 on 2025-12-28 19:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('encuestas', '0002_evaluacionempresa_and_more'),
        ('respuestas', '0004_remove_calculonivel_calculos_ni_asignac_781ef9_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='calculonivel',
            name='evaluacion_empresa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='calculos_nivel', to='encuestas.evaluacionempresa', verbose_name='Evaluación Empresa'),
        ),
    ]
