# Generated by Django 5.2.12 on 2026-04-23 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('respuestas', '0004_calculonivel_fecha_remediacion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calculonivel',
            name='gap',
            field=models.DecimalField(decimal_places=2, help_text='Diferencia: Nivel Deseado - Nivel Actual', max_digits=4, verbose_name='GAP'),
        ),
        migrations.AlterField(
            model_name='calculonivel',
            name='nivel_actual',
            field=models.DecimalField(decimal_places=2, help_text='Promedio de nivel_madurez de todas las respuestas del usuario', max_digits=4, verbose_name='Nivel Actual'),
        ),
    ]
