# Generated by Django 5.0 on 2026-01-13 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('respuestas', '0005_calculonivel_evaluacion_empresa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evidencia',
            name='archivo',
            field=models.CharField(help_text='Ruta del archivo en Supabase Storage (ej: evidencias/empresa_123/archivo.pdf)', max_length=500, verbose_name='Ruta del Archivo en Supabase'),
        ),
        migrations.AlterField(
            model_name='respuesta',
            name='justificacion_madurez',
            field=models.TextField(blank=True, default='', help_text='Explicación de por qué se considera ese nivel de madurez (OPCIONAL)', verbose_name='Justificación del Nivel de Madurez'),
        ),
    ]
