# Generated by Django 5.0 on 2026-01-19 03:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('respuestas', '0006_alter_evidencia_archivo_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Iniciativa',
        ),
    ]
