# Generated by Django 5.2.11 on 2026-03-07 23:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asignaciones', '0005_asignacion_evaluacion_empresa_and_more'),
        ('documentos', '0003_alter_documento_version'),
        ('encuestas', '0002_evaluacionempresa_and_more'),
        ('respuestas', '0007_delete_iniciativa'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='tipodocumento',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='tipodocumento',
            name='empresa',
        ),
        migrations.RemoveIndex(
            model_name='respuesta',
            name='respuestas_modific_9f3898_idx',
        ),
        migrations.RemoveField(
            model_name='respuesta',
            name='justificacion_madurez',
        ),
        migrations.AddField(
            model_name='evidencia',
            name='documento_oficial',
            field=models.ForeignKey(blank=True, help_text='Si selecciona un documento del Módulo de Gestión Documental, se vinculará aquí.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='evidencias_utilizadas', to='documentos.documento', verbose_name='Documento del Maestro'),
        ),
        migrations.AddField(
            model_name='respuesta',
            name='auditado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='respuestas_auditadas', to=settings.AUTH_USER_MODEL, verbose_name='Auditado Por'),
        ),
        migrations.AddField(
            model_name='respuesta',
            name='calificacion_auditor',
            field=models.CharField(blank=True, choices=[('SI_CUMPLE', 'Sí Cumple'), ('CUMPLE_PARCIAL', 'Cumple Parcialmente'), ('NO_CUMPLE', 'No Cumple')], help_text='SI_CUMPLE / CUMPLE_PARCIAL / NO_CUMPLE — asignado por el Auditor', max_length=20, null=True, verbose_name='Calificación del Auditor'),
        ),
        migrations.AddField(
            model_name='respuesta',
            name='comentarios_auditor',
            field=models.TextField(blank=True, default='', help_text='Observaciones del auditor sobre la respuesta', verbose_name='Comentarios del Auditor'),
        ),
        migrations.AddField(
            model_name='respuesta',
            name='fecha_auditoria',
            field=models.DateTimeField(blank=True, help_text='Fecha en que el auditor calificó esta respuesta', null=True, verbose_name='Fecha de Auditoría'),
        ),
        migrations.AddField(
            model_name='respuesta',
            name='recomendaciones_auditor',
            field=models.TextField(blank=True, default='', help_text='Qué debe mejorar la empresa para subir de nivel', verbose_name='Recomendaciones del Auditor'),
        ),
        migrations.AlterField(
            model_name='calculonivel',
            name='asignacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calculos_nivel', to='asignaciones.asignacion', verbose_name='Asignación'),
        ),
        migrations.AlterField(
            model_name='evidencia',
            name='respuesta',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='evidencias', to='respuestas.respuesta', verbose_name='Respuesta'),
        ),
        migrations.AlterField(
            model_name='respuesta',
            name='comentarios_adicionales',
            field=models.TextField(blank=True, default='', verbose_name='Comentarios Adicionales del Usuario'),
        ),
        migrations.AlterField(
            model_name='respuesta',
            name='estado',
            field=models.CharField(choices=[('borrador', 'Borrador'), ('enviado', 'Enviado'), ('pendiente_auditoria', 'Pendiente de Auditoría'), ('auditado', 'Auditado'), ('modificado_admin', 'Modificado por Admin')], default='borrador', max_length=25, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='respuesta',
            name='justificacion',
            field=models.TextField(blank=True, default='', help_text='Obligatorio siempre (mínimo 10 caracteres). Para NO_APLICA: explica por qué no aplica.', verbose_name='Justificación del Usuario'),
        ),
        migrations.AlterField(
            model_name='respuesta',
            name='nivel_madurez',
            field=models.DecimalField(decimal_places=1, default=0.0, help_text='Asignado por el auditor (0–5 en incrementos de 0.5)', max_digits=2, verbose_name='Nivel de Madurez'),
        ),
        migrations.AlterField(
            model_name='respuesta',
            name='respuesta',
            field=models.CharField(blank=True, choices=[('NO_APLICA', 'No Aplica'), ('SI_CUMPLE', 'Sí Cumple'), ('CUMPLE_PARCIAL', 'Cumple Parcialmente'), ('NO_CUMPLE', 'No Cumple')], help_text='El usuario solo puede marcar NO_APLICA. Si deja vacío, sube evidencias para que el auditor califique.', max_length=20, null=True, verbose_name='Respuesta del Usuario'),
        ),
        migrations.AddIndex(
            model_name='respuesta',
            index=models.Index(fields=['auditado_por'], name='respuestas_auditad_df6fa1_idx'),
        ),
        migrations.DeleteModel(
            name='TipoDocumento',
        ),
    ]
