# Generated by Django 5.0 on 2026-02-23 03:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asignaciones_iq', '0003_respuestaevaluacioniq'),
        ('respuestas', '0007_delete_iniciativa'),
    ]

    operations = [
        migrations.AddField(
            model_name='evidencia',
            name='respuesta_iq',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='evidencias', to='asignaciones_iq.respuestaevaluacioniq', verbose_name='Respuesta IQ'),
        ),
    ]
