# Generated by Django 5.0 on 2026-02-23 05:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('respuestas', '0008_evidencia_respuesta_iq'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evidencia',
            name='respuesta',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='evidencias', to='respuestas.respuesta', verbose_name='Respuesta'),
        ),
    ]
