# Generated by Django 5.2.11 on 2026-03-08 09:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('respuestas', '0008_alter_tipodocumento_unique_together_and_more'),
        ('respuestas', '0010_remove_respuesta_respuestas_modific_9f3898_idx_and_more'),
    ]

    operations = [
    ]
