# Generated by Django 5.0 on 2025-10-31 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('empresas', '0002_empresa_pais_empresa_pais_otro_empresa_sector_and_more'),
        ('usuarios', '0004_alter_usuario_empresa'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usuario',
            options={'ordering': ['email'], 'verbose_name': 'Usuario', 'verbose_name_plural': 'Usuarios'},
        ),
        migrations.AlterField(
            model_name='usuario',
            name='rol',
            field=models.CharField(choices=[('superadmin', 'Super Administrador'), ('administrador', 'Administrador'), ('usuario', 'Usuario'), ('auditor', 'Auditor')], default='usuario', max_length=20, verbose_name='Rol'),
        ),
        migrations.AddIndex(
            model_name='usuario',
            index=models.Index(fields=['rol'], name='usuarios_rol_936bfb_idx'),
        ),
    ]
