# Generated by Django 5.2.12 on 2026-04-22 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0005_alter_usuario_options_alter_usuario_rol_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='rol',
            field=models.CharField(choices=[('superadmin', 'Super Administrador'), ('administrador', 'Administrador'), ('usuario', 'Usuario'), ('analista_riesgos', 'Analista de Riesgos'), ('auditor', 'Auditor')], default='usuario', max_length=20, verbose_name='Rol'),
        ),
    ]
