# Generated by Django 5.2.12 on 2026-03-10 02:17

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('empresas', '0002_empresa_pais_empresa_pais_otro_empresa_sector_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Norma',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('activo', models.BooleanField(default=True)),
                ('nombre', models.CharField(max_length=255, verbose_name='Nombre de la Norma')),
                ('descripcion', models.TextField(blank=True, null=True, verbose_name='Descripción')),
                ('empresa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='empresas.empresa')),
            ],
            options={
                'verbose_name': 'Norma',
                'verbose_name_plural': 'Normas',
                'db_table': 'normas',
            },
        ),
        migrations.CreateModel(
            name='Proceso',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('activo', models.BooleanField(default=True)),
                ('nombre', models.CharField(max_length=255, verbose_name='Nombre del Proceso')),
                ('sigla', models.CharField(help_text='Ej: TI, RRHH', max_length=10, verbose_name='Sigla')),
                ('empresa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='empresas.empresa')),
            ],
            options={
                'verbose_name': 'Proceso',
                'verbose_name_plural': 'Procesos',
                'db_table': 'procesos',
            },
        ),
        migrations.CreateModel(
            name='TipoDocumento',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('activo', models.BooleanField(default=True)),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre del Tipo')),
                ('abreviatura', models.CharField(help_text='Ej: POL, MAN, REG', max_length=10)),
                ('nivel_jerarquico', models.PositiveSmallIntegerField(default=3, help_text='1: Estratégico, 2: Táctico, 3: Operativo, 4: Instructivo')),
                ('requiere_word_y_pdf', models.BooleanField(default=True, help_text='Si es True, el sistema exigirá subir ambos archivos (.pdf y .docx)')),
                ('empresa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='empresas.empresa')),
            ],
            options={
                'verbose_name': 'Tipo de Documento',
                'verbose_name_plural': 'Tipos de Documento',
                'db_table': 'tipos_documento',
            },
        ),
        migrations.CreateModel(
            name='Documento',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('activo', models.BooleanField(default=True)),
                ('codigo', models.CharField(max_length=50, verbose_name='Código de Documento')),
                ('titulo', models.CharField(max_length=255, verbose_name='Título')),
                ('version', models.CharField(default='1.0', help_text='Permite decimales ej: 1.0, 1.1, 2.0', max_length=10, verbose_name='Versión')),
                ('objetivo', models.TextField(blank=True, verbose_name='Objetivo / Propósito')),
                ('alcance', models.TextField(blank=True, verbose_name='Alcance (Org/Depto/Proceso)')),
                ('nivel_confidencialidad', models.CharField(choices=[('publico', 'Público'), ('interno', 'Uso Interno'), ('confidencial', 'Confidencial'), ('secreto', 'Secreto'), ('estrategico', 'Estratégico')], default='interno', max_length=20)),
                ('frecuencia_revision', models.CharField(choices=[('mensual', 'Mensual'), ('trimestral', 'Trimestral'), ('semestral', 'Semestral'), ('anual', 'Anual'), ('no_aplica', 'No Aplica')], default='anual', max_length=20)),
                ('periodo_retencion', models.PositiveIntegerField(default=5, verbose_name='Periodo de Retención (Años)')),
                ('archivo_pdf', models.CharField(blank=True, max_length=500, null=True, verbose_name='Ruta PDF (.pdf)')),
                ('archivo_editable', models.CharField(blank=True, max_length=500, null=True, verbose_name='Ruta Editable (.docx, .xlsx)')),
                ('estado', models.CharField(choices=[('borrador', 'Borrador'), ('en_revision', 'En Revisión'), ('vigente', 'Vigente'), ('obsoleto', 'Obsoleto')], default='borrador', max_length=20)),
                ('fecha_emision', models.DateField(blank=True, null=True)),
                ('fecha_proxima_revision', models.DateField(blank=True, null=True, verbose_name='Fecha Próxima Revisión')),
                ('aprobado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='docs_aprobados', to=settings.AUTH_USER_MODEL)),
                ('elaborado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='docs_elaborados', to=settings.AUTH_USER_MODEL)),
                ('empresa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='empresas.empresa')),
                ('revisado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='docs_revisados', to=settings.AUTH_USER_MODEL)),
                ('norma', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documentos', to='documentos.norma', verbose_name='Referencia Normativa')),
                ('proceso', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='documentos', to='documentos.proceso', verbose_name='Proceso Dueño')),
                ('tipo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='documentos', to='documentos.tipodocumento', verbose_name='Tipo de Documento')),
            ],
            options={
                'verbose_name': 'Documento',
                'verbose_name_plural': 'Documentos',
                'db_table': 'documentos_maestros',
                'ordering': ['-fecha_creacion'],
                'unique_together': {('empresa', 'codigo')},
            },
        ),
    ]
