# Generated by Django 5.0 on 2026-02-17 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documentos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tipodocumento',
            name='requiere_word_y_pdf',
            field=models.BooleanField(default=True, help_text='Si es True, el sistema exigirá subir ambos archivos (.pdf y .docx)'),
        ),
    ]
