# Generated by Django 5.2.11 on 2026-02-20 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documentos', '0002_alter_tipodocumento_requiere_word_y_pdf'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documento',
            name='version',
            field=models.CharField(default='1.0', help_text='Permite decimales ej: 1.0, 1.1, 2.0', max_length=10, verbose_name='Versión'),
        ),
    ]
