# Generated by Django 5.0 on 2025-11-10 08:16

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('empresas', '0002_empresa_pais_empresa_pais_otro_empresa_sector_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Encuesta',
            fields=[
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, verbose_name='Fecha de Actualización')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=300, verbose_name='Nombre')),
                ('descripcion', models.TextField(blank=True, verbose_name='Descripción')),
                ('version', models.CharField(default='1.0', max_length=20, verbose_name='Versión')),
                ('es_plantilla', models.BooleanField(default=True, verbose_name='Es Plantilla')),
            ],
            options={
                'verbose_name': 'Encuesta',
                'verbose_name_plural': 'Encuestas',
                'db_table': 'encuestas',
                'ordering': ['-fecha_creacion'],
                'indexes': [models.Index(fields=['nombre'], name='encuestas_nombre_25b59b_idx'), models.Index(fields=['es_plantilla', 'activo'], name='encuestas_es_plan_f4e07b_idx')],
            },
        ),
        migrations.CreateModel(
            name='Dimension',
            fields=[
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, verbose_name='Fecha de Actualización')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('codigo', models.CharField(max_length=20, verbose_name='Código')),
                ('nombre', models.CharField(max_length=200, verbose_name='Nombre')),
                ('descripcion', models.TextField(blank=True, verbose_name='Descripción')),
                ('orden', models.PositiveIntegerField(default=0, verbose_name='Orden')),
                ('encuesta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dimensiones', to='encuestas.encuesta', verbose_name='Encuesta')),
            ],
            options={
                'verbose_name': 'Dimensión',
                'verbose_name_plural': 'Dimensiones',
                'db_table': 'dimensiones',
                'ordering': ['encuesta', 'orden', 'codigo'],
            },
        ),
        migrations.CreateModel(
            name='Pregunta',
            fields=[
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, verbose_name='Fecha de Actualización')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('codigo', models.CharField(max_length=50, verbose_name='Código')),
                ('titulo', models.CharField(max_length=500, verbose_name='Título')),
                ('texto', models.TextField(verbose_name='Texto de la Pregunta')),
                ('peso', models.DecimalField(decimal_places=2, default=1.0, help_text='Ponderación de la pregunta en el cálculo', max_digits=5, verbose_name='Peso')),
                ('obligatoria', models.BooleanField(default=True, verbose_name='Obligatoria')),
                ('orden', models.PositiveIntegerField(default=0, verbose_name='Orden')),
                ('dimension', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='preguntas', to='encuestas.dimension', verbose_name='Dimensión')),
            ],
            options={
                'verbose_name': 'Pregunta',
                'verbose_name_plural': 'Preguntas',
                'db_table': 'preguntas',
                'ordering': ['dimension', 'orden', 'codigo'],
            },
        ),
        migrations.CreateModel(
            name='NivelReferencia',
            fields=[
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, verbose_name='Fecha de Actualización')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('numero', models.IntegerField(choices=[(1, 'Nivel 1'), (2, 'Nivel 2'), (3, 'Nivel 3'), (4, 'Nivel 4'), (5, 'Nivel 5')], verbose_name='Número de Nivel')),
                ('descripcion', models.TextField(verbose_name='Descripción del Nivel')),
                ('recomendaciones', models.TextField(blank=True, help_text='Qué hacer para alcanzar este nivel', verbose_name='Recomendaciones')),
                ('pregunta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='niveles_referencia', to='encuestas.pregunta', verbose_name='Pregunta')),
            ],
            options={
                'verbose_name': 'Nivel de Referencia',
                'verbose_name_plural': 'Niveles de Referencia',
                'db_table': 'niveles_referencia',
                'ordering': ['pregunta', 'numero'],
            },
        ),
        migrations.CreateModel(
            name='ConfigNivelDeseado',
            fields=[
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, verbose_name='Fecha de Actualización')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nivel_deseado', models.IntegerField(choices=[(1, 'Nivel 1'), (2, 'Nivel 2'), (3, 'Nivel 3'), (4, 'Nivel 4'), (5, 'Nivel 5')], verbose_name='Nivel Deseado')),
                ('motivo_cambio', models.TextField(blank=True, help_text='Razón por la que se estableció este nivel', verbose_name='Motivo del Cambio')),
                ('configurado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='configuraciones_realizadas', to=settings.AUTH_USER_MODEL, verbose_name='Configurado Por')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='configuraciones_nivel', to='empresas.empresa', verbose_name='Empresa')),
                ('dimension', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='configuraciones_nivel', to='encuestas.dimension', verbose_name='Dimensión')),
            ],
            options={
                'verbose_name': 'Configuración Nivel Deseado',
                'verbose_name_plural': 'Configuraciones Niveles Deseados',
                'db_table': 'config_niveles_deseados',
                'ordering': ['-fecha_creacion'],
                'indexes': [models.Index(fields=['dimension', 'empresa'], name='config_nive_dimensi_e54c44_idx'), models.Index(fields=['empresa'], name='config_nive_empresa_65b283_idx')],
                'unique_together': {('dimension', 'empresa')},
            },
        ),
        migrations.AddIndex(
            model_name='dimension',
            index=models.Index(fields=['encuesta', 'orden'], name='dimensiones_encuest_59431e_idx'),
        ),
        migrations.AddIndex(
            model_name='dimension',
            index=models.Index(fields=['codigo'], name='dimensiones_codigo_3a7922_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='dimension',
            unique_together={('encuesta', 'codigo')},
        ),
        migrations.AddIndex(
            model_name='pregunta',
            index=models.Index(fields=['dimension', 'orden'], name='preguntas_dimensi_7bd988_idx'),
        ),
        migrations.AddIndex(
            model_name='pregunta',
            index=models.Index(fields=['codigo'], name='preguntas_codigo_a5ac78_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='pregunta',
            unique_together={('dimension', 'codigo')},
        ),
        migrations.AddIndex(
            model_name='nivelreferencia',
            index=models.Index(fields=['pregunta', 'numero'], name='niveles_ref_pregunt_a46970_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='nivelreferencia',
            unique_together={('pregunta', 'numero')},
        ),
    ]
