# Generated by Django 5.0 on 2025-12-28 19:58

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0002_empresa_pais_empresa_pais_otro_empresa_sector_and_more'),
        ('encuestas', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EvaluacionEmpresa',
            fields=[
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, verbose_name='Fecha de Actualización')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('fecha_asignacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Asignación')),
                ('fecha_limite', models.DateField(help_text='Fecha límite para completar toda la evaluación', verbose_name='Fecha Límite Global')),
                ('fecha_completado', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Completado')),
                ('estado', models.CharField(choices=[('activa', 'Activa'), ('en_progreso', 'En Progreso'), ('completada', 'Completada'), ('vencida', 'Vencida'), ('cancelada', 'Cancelada')], default='activa', max_length=20, verbose_name='Estado')),
                ('observaciones', models.TextField(blank=True, default='', verbose_name='Observaciones')),
                ('total_dimensiones', models.IntegerField(default=0, verbose_name='Total de Dimensiones')),
                ('dimensiones_asignadas', models.IntegerField(default=0, verbose_name='Dimensiones Asignadas a Usuarios')),
                ('dimensiones_completadas', models.IntegerField(default=0, verbose_name='Dimensiones Completadas')),
                ('porcentaje_avance', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Porcentaje de Avance')),
            ],
            options={
                'verbose_name': 'Evaluación Empresa',
                'verbose_name_plural': 'Evaluaciones Empresas',
                'db_table': 'evaluaciones_empresas',
                'ordering': ['-fecha_asignacion'],
            },
        ),
        migrations.RemoveIndex(
            model_name='configniveldeseado',
            name='config_nive_dimensi_e54c44_idx',
        ),
        migrations.AddField(
            model_name='evaluacionempresa',
            name='administrador',
            field=models.ForeignKey(help_text='Administrador de la empresa a quien se asignó', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='evaluaciones_administradas', to=settings.AUTH_USER_MODEL, verbose_name='Administrador Responsable'),
        ),
        migrations.AddField(
            model_name='evaluacionempresa',
            name='asignado_por',
            field=models.ForeignKey(help_text='SuperAdmin que asignó la evaluación', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='evaluaciones_asignadas_creadas', to=settings.AUTH_USER_MODEL, verbose_name='Asignado Por'),
        ),
        migrations.AddField(
            model_name='evaluacionempresa',
            name='empresa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluaciones_asignadas', to='empresas.empresa', verbose_name='Empresa'),
        ),
        migrations.AddField(
            model_name='evaluacionempresa',
            name='encuesta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asignaciones_empresas', to='encuestas.encuesta', verbose_name='Encuesta'),
        ),
        migrations.AlterUniqueTogether(
            name='configniveldeseado',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='configniveldeseado',
            name='evaluacion_empresa',
            field=models.ForeignKey(blank=True, help_text='A qué evaluación específica pertenece esta configuración', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='configuraciones_nivel', to='encuestas.evaluacionempresa', verbose_name='Evaluación Empresa'),
        ),
        migrations.AlterUniqueTogether(
            name='configniveldeseado',
            unique_together={('evaluacion_empresa', 'dimension')},
        ),
        migrations.AddIndex(
            model_name='configniveldeseado',
            index=models.Index(fields=['evaluacion_empresa', 'dimension'], name='config_nive_evaluac_8bd2a5_idx'),
        ),
        migrations.AddIndex(
            model_name='evaluacionempresa',
            index=models.Index(fields=['empresa', 'estado'], name='evaluacione_empresa_a6471e_idx'),
        ),
        migrations.AddIndex(
            model_name='evaluacionempresa',
            index=models.Index(fields=['administrador'], name='evaluacione_adminis_34357f_idx'),
        ),
        migrations.AddIndex(
            model_name='evaluacionempresa',
            index=models.Index(fields=['fecha_limite'], name='evaluacione_fecha_l_17b3f2_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='evaluacionempresa',
            unique_together={('empresa', 'encuesta', 'activo')},
        ),
    ]
